/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "editor_callbacks.h"
#include "editor_interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_editor_window (void)
{
  GtkWidget *editor_window;
  GdkPixbuf *editor_window_icon_pixbuf;
  GtkWidget *vbox36;
  GtkWidget *hbox86;
  GtkWidget *vbox42;
  GtkWidget *label138;
  GtkWidget *entry_definitions_file;
  GtkWidget *button_choose_def;
  GtkWidget *image68;
  GtkWidget *hbox50;
  GtkWidget *vbox37;
  GtkWidget *label73;
  GtkWidget *combo_team_file;
  GtkWidget *entry_country_file;
  GtkWidget *button_browse_team_files;
  GtkWidget *image56;
  GtkWidget *hseparator16;
  GtkWidget *hbox69;
  GtkWidget *vbox38;
  GtkWidget *label75;
  GtkWidget *hbox51;
  GtkWidget *combo_team_names;
  GtkWidget *entry_team;
  GtkWidget *eventbox2;
  GtkWidget *hbox98;
  GtkWidget *label183;
  GtkWidget *entry_team_name;
  GtkWidget *vseparator123;
  GtkWidget *vbox41;
  GtkWidget *label_structures;
  GtkWidget *hbox85;
  GtkWidget *entry_structure1;
  GtkWidget *entry_structure2;
  GtkWidget *button_change_structures;
  GtkWidget *image63;
  GtkWidget *vseparator124;
  GtkWidget *vbox49;
  GtkWidget *eventbox1;
  GtkWidget *vbox50;
  GtkWidget *label182;
  GtkObject *spinbutton_average_skill_adj;
  GtkWidget *spinbutton_average_skill;
  GtkWidget *hseparator13;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview_players;
  GtkWidget *hbox94;
  GtkWidget *vbox48;
  GtkWidget *label181;
  GtkWidget *label_number;
  GtkWidget *vbox44;
  GtkWidget *label174;
  GtkWidget *entry_name;
  GtkWidget *vbox45;
  GtkWidget *label175;
  GtkObject *spinbutton_skill_adj;
  GtkWidget *spinbutton_skill;
  GtkWidget *vbox46;
  GtkWidget *label176;
  GtkObject *spinbutton_talent_adj;
  GtkWidget *spinbutton_talent;
  GtkWidget *vbox47;
  GtkWidget *label177;
  GtkWidget *hbox97;
  GtkObject *spinbutton_birth_year_adj;
  GtkWidget *spinbutton_birth_year;
  GtkObject *spinbutton_birth_month_adj;
  GtkWidget *spinbutton_birth_month;
  GtkWidget *button_update;
  GtkWidget *image72;
  GtkWidget *button_prev;
  GtkWidget *image77;
  GtkWidget *button_next;
  GtkWidget *image78;
  GtkWidget *hseparator15;
  GtkWidget *hbox87;
  GtkWidget *hbox84;
  GtkWidget *label137;
  GtkObject *spinbutton_swap1_adj;
  GtkWidget *spinbutton_swap1;
  GtkWidget *button_swap;
  GtkWidget *image66;
  GtkObject *spinbutton_swap2_adj;
  GtkWidget *spinbutton_swap2;
  GtkWidget *hbox88;
  GtkWidget *label171;
  GtkObject *spinbutton_move_adj;
  GtkWidget *spinbutton_move;
  GtkWidget *button_up;
  GtkWidget *alignment22;
  GtkWidget *hbox89;
  GtkWidget *image70;
  GtkWidget *label172;
  GtkWidget *button_down;
  GtkWidget *alignment23;
  GtkWidget *hbox90;
  GtkWidget *image71;
  GtkWidget *label173;
  GtkWidget *hseparator19;
  GtkWidget *hbox64;
  GtkWidget *button_editor_help;
  GtkWidget *alignment25;
  GtkWidget *hbox96;
  GtkWidget *image74;
  GtkWidget *label179;
  GtkWidget *button_exit;
  GtkWidget *alignment26;
  GtkWidget *hbox99;
  GtkWidget *image79;
  GtkWidget *label184;
  GtkWidget *button_save;
  GtkWidget *alignment18;
  GtkWidget *hbox67;
  GtkWidget *image61;
  GtkWidget *label94;
  GtkWidget *button_import;
  GtkWidget *alignment28;
  GtkWidget *hbox101;
  GtkWidget *image81;
  GtkWidget *label186;
  GtkWidget *button_export;
  GtkWidget *alignment27;
  GtkWidget *hbox100;
  GtkWidget *image80;
  GtkWidget *label185;
  GtkWidget *button_play_ws;
  GtkWidget *alignment24;
  GtkWidget *hbox95;
  GtkWidget *image73;
  GtkWidget *label178;
  GtkWidget *button_save_play;
  GtkWidget *alignment21;
  GtkWidget *hbox71;
  GtkWidget *image65;
  GtkWidget *label170;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  editor_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (editor_window), 6);
  gtk_window_set_title (GTK_WINDOW (editor_window), _("Bygfoot Team Editor"));
  gtk_window_set_position (GTK_WINDOW (editor_window), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (editor_window), 400, 600);
  editor_window_icon_pixbuf = create_pixbuf ("bygfoot_team_editor_icon.png");
  if (editor_window_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (editor_window), editor_window_icon_pixbuf);
      gdk_pixbuf_unref (editor_window_icon_pixbuf);
    }

  vbox36 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox36);
  gtk_container_add (GTK_CONTAINER (editor_window), vbox36);

  hbox86 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox86);
  gtk_box_pack_start (GTK_BOX (vbox36), hbox86, FALSE, TRUE, 0);

  vbox42 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox42);
  gtk_box_pack_start (GTK_BOX (hbox86), vbox42, TRUE, TRUE, 0);

  label138 = gtk_label_new (_("Team definitions file"));
  gtk_widget_show (label138);
  gtk_box_pack_start (GTK_BOX (vbox42), label138, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label138), GTK_JUSTIFY_LEFT);

  entry_definitions_file = gtk_entry_new ();
  gtk_widget_show (entry_definitions_file);
  gtk_box_pack_start (GTK_BOX (vbox42), entry_definitions_file, FALSE, FALSE, 3);
  gtk_tooltips_set_tip (tooltips, entry_definitions_file, _("The file team definitions are read from and written to. Default is $HOME/.bygfoot/text_files/teams."), NULL);

  button_choose_def = gtk_button_new ();
  gtk_widget_show (button_choose_def);
  gtk_box_pack_start (GTK_BOX (hbox86), button_choose_def, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_choose_def), 3);
  gtk_tooltips_set_tip (tooltips, button_choose_def, _("Select file"), NULL);

  image68 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image68);
  gtk_container_add (GTK_CONTAINER (button_choose_def), image68);

  hbox50 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox50);
  gtk_box_pack_start (GTK_BOX (vbox36), hbox50, FALSE, TRUE, 5);

  vbox37 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox37);
  gtk_box_pack_start (GTK_BOX (hbox50), vbox37, TRUE, TRUE, 0);

  label73 = gtk_label_new (_("Country file"));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (vbox37), label73, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label73), GTK_JUSTIFY_LEFT);

  combo_team_file = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_team_file)->popwin),
                     "GladeParentKey", combo_team_file);
  gtk_widget_show (combo_team_file);
  gtk_box_pack_start (GTK_BOX (vbox37), combo_team_file, FALSE, FALSE, 3);

  entry_country_file = GTK_COMBO (combo_team_file)->entry;
  gtk_widget_show (entry_country_file);
  gtk_tooltips_set_tip (tooltips, entry_country_file, _("File with the team names (country-specific, e.g. country_eng for the English teams)"), NULL);
  gtk_entry_set_text (GTK_ENTRY (entry_country_file), _("Choose or enter country file"));

  button_browse_team_files = gtk_button_new ();
  gtk_widget_show (button_browse_team_files);
  gtk_box_pack_start (GTK_BOX (hbox50), button_browse_team_files, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_browse_team_files), 3);
  gtk_tooltips_set_tip (tooltips, button_browse_team_files, _("Select file"), NULL);

  image56 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image56);
  gtk_container_add (GTK_CONTAINER (button_browse_team_files), image56);

  hseparator16 = gtk_hseparator_new ();
  gtk_widget_show (hseparator16);
  gtk_box_pack_start (GTK_BOX (vbox36), hseparator16, FALSE, FALSE, 0);
  gtk_widget_set_size_request (hseparator16, 1, 10);

  hbox69 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox69);
  gtk_box_pack_start (GTK_BOX (vbox36), hbox69, FALSE, TRUE, 0);

  vbox38 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox38);
  gtk_box_pack_start (GTK_BOX (hbox69), vbox38, TRUE, TRUE, 0);

  label75 = gtk_label_new (_("Teams in the country file"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (vbox38), label75, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label75), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label75), 0.46, 0.5);

  hbox51 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox51);
  gtk_box_pack_start (GTK_BOX (vbox38), hbox51, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox51), 2);

  combo_team_names = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_team_names)->popwin),
                     "GladeParentKey", combo_team_names);
  gtk_widget_show (combo_team_names);
  gtk_box_pack_start (GTK_BOX (hbox51), combo_team_names, TRUE, TRUE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (combo_team_names), TRUE, TRUE);

  entry_team = GTK_COMBO (combo_team_names)->entry;
  gtk_widget_show (entry_team);
  gtk_tooltips_set_tip (tooltips, entry_team, _("Teams found in the country file. Choose one to edit it."), NULL);
  gtk_editable_set_editable (GTK_EDITABLE (entry_team), FALSE);

  eventbox2 = gtk_event_box_new ();
  gtk_widget_show (eventbox2);
  gtk_box_pack_start (GTK_BOX (vbox38), eventbox2, TRUE, TRUE, 0);

  hbox98 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox98);
  gtk_container_add (GTK_CONTAINER (eventbox2), hbox98);
  gtk_container_set_border_width (GTK_CONTAINER (hbox98), 2);

  label183 = gtk_label_new (_("Change team name to  "));
  gtk_widget_show (label183);
  gtk_box_pack_start (GTK_BOX (hbox98), label183, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label183), GTK_JUSTIFY_LEFT);

  entry_team_name = gtk_entry_new ();
  gtk_widget_show (entry_team_name);
  gtk_box_pack_start (GTK_BOX (hbox98), entry_team_name, TRUE, TRUE, 0);
  gtk_entry_set_max_length (GTK_ENTRY (entry_team_name), 49);

  vseparator123 = gtk_vseparator_new ();
  gtk_widget_show (vseparator123);
  gtk_box_pack_start (GTK_BOX (hbox69), vseparator123, FALSE, TRUE, 0);
  gtk_widget_set_size_request (vseparator123, 10, 1);

  vbox41 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox41);
  gtk_box_pack_start (GTK_BOX (hbox69), vbox41, FALSE, FALSE, 0);

  label_structures = gtk_label_new (_("Team structures"));
  gtk_widget_show (label_structures);
  gtk_box_pack_start (GTK_BOX (vbox41), label_structures, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label_structures), GTK_JUSTIFY_LEFT);

  hbox85 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox85);
  gtk_box_pack_start (GTK_BOX (vbox41), hbox85, TRUE, TRUE, 0);

  entry_structure1 = gtk_entry_new ();
  gtk_widget_show (entry_structure1);
  gtk_box_pack_start (GTK_BOX (hbox85), entry_structure1, TRUE, TRUE, 2);
  gtk_tooltips_set_tip (tooltips, entry_structure1, _("These digits must add up to 10."), NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry_structure1), 3);
  gtk_entry_set_text (GTK_ENTRY (entry_structure1), _("442"));
  gtk_entry_set_width_chars (GTK_ENTRY (entry_structure1), 4);

  entry_structure2 = gtk_entry_new ();
  gtk_widget_show (entry_structure2);
  gtk_box_pack_start (GTK_BOX (hbox85), entry_structure2, TRUE, TRUE, 2);
  gtk_tooltips_set_tip (tooltips, entry_structure2, _("These digits must add up to 8."), NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry_structure2), 3);
  gtk_entry_set_text (GTK_ENTRY (entry_structure2), _("332"));
  gtk_entry_set_width_chars (GTK_ENTRY (entry_structure2), 4);

  button_change_structures = gtk_button_new ();
  gtk_widget_show (button_change_structures);
  gtk_box_pack_start (GTK_BOX (hbox85), button_change_structures, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_change_structures), 3);
  gtk_tooltips_set_tip (tooltips, button_change_structures, _("Apply changes"), NULL);

  image63 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image63);
  gtk_container_add (GTK_CONTAINER (button_change_structures), image63);

  vseparator124 = gtk_vseparator_new ();
  gtk_widget_show (vseparator124);
  gtk_box_pack_start (GTK_BOX (hbox69), vseparator124, FALSE, FALSE, 0);
  gtk_widget_set_size_request (vseparator124, 10, 1);

  vbox49 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox49);
  gtk_box_pack_start (GTK_BOX (hbox69), vbox49, FALSE, FALSE, 3);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_box_pack_start (GTK_BOX (vbox49), eventbox1, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, eventbox1, _("The average skills of the five leagues in the first season are: 8.0, 7.0, 6.0, 5.0 and 4.0."), NULL);

  vbox50 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox50);
  gtk_container_add (GTK_CONTAINER (eventbox1), vbox50);

  label182 = gtk_label_new (_("Average skill"));
  gtk_widget_show (label182);
  gtk_box_pack_start (GTK_BOX (vbox50), label182, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label182), GTK_JUSTIFY_LEFT);

  spinbutton_average_skill_adj = gtk_adjustment_new (1, 1, 9.9, 0.01, 10, 10);
  spinbutton_average_skill = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_average_skill_adj), 0.01, 2);
  gtk_widget_show (spinbutton_average_skill);
  gtk_box_pack_start (GTK_BOX (vbox50), spinbutton_average_skill, FALSE, FALSE, 5);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_average_skill), TRUE);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (spinbutton_average_skill), TRUE);

  hseparator13 = gtk_hseparator_new ();
  gtk_widget_show (hseparator13);
  gtk_box_pack_start (GTK_BOX (vbox36), hseparator13, FALSE, FALSE, 0);
  gtk_widget_set_size_request (hseparator13, 1, 15);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox36), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  treeview_players = gtk_tree_view_new ();
  gtk_widget_show (treeview_players);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview_players);
  gtk_tree_view_set_enable_search (GTK_TREE_VIEW (treeview_players), FALSE);

  hbox94 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox94);
  gtk_box_pack_start (GTK_BOX (vbox36), hbox94, FALSE, FALSE, 5);

  vbox48 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox48);
  gtk_box_pack_start (GTK_BOX (hbox94), vbox48, FALSE, FALSE, 0);

  label181 = gtk_label_new (_("Nr"));
  gtk_widget_show (label181);
  gtk_box_pack_start (GTK_BOX (vbox48), label181, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label181), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label181), 0, 2);

  label_number = gtk_label_new (_("1"));
  gtk_widget_show (label_number);
  gtk_box_pack_start (GTK_BOX (vbox48), label_number, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label_number), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label_number), 4, 3);

  vbox44 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox44);
  gtk_box_pack_start (GTK_BOX (hbox94), vbox44, TRUE, TRUE, 0);

  label174 = gtk_label_new (_("Name"));
  gtk_widget_show (label174);
  gtk_box_pack_start (GTK_BOX (vbox44), label174, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label174), GTK_JUSTIFY_LEFT);

  entry_name = gtk_entry_new ();
  gtk_widget_show (entry_name);
  gtk_box_pack_start (GTK_BOX (vbox44), entry_name, FALSE, FALSE, 3);
  gtk_entry_set_max_length (GTK_ENTRY (entry_name), 18);
  gtk_entry_set_width_chars (GTK_ENTRY (entry_name), 18);

  vbox45 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox45);
  gtk_box_pack_start (GTK_BOX (hbox94), vbox45, TRUE, TRUE, 0);

  label175 = gtk_label_new (_("Skill"));
  gtk_widget_show (label175);
  gtk_box_pack_start (GTK_BOX (vbox45), label175, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label175), GTK_JUSTIFY_LEFT);

  spinbutton_skill_adj = gtk_adjustment_new (5, 1, 9.9, 0.1, 10, 10);
  spinbutton_skill = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_skill_adj), 0.1, 1);
  gtk_widget_show (spinbutton_skill);
  gtk_box_pack_start (GTK_BOX (vbox45), spinbutton_skill, FALSE, FALSE, 3);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_skill), TRUE);

  vbox46 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox46);
  gtk_box_pack_start (GTK_BOX (hbox94), vbox46, TRUE, TRUE, 0);

  label176 = gtk_label_new (_("Talent"));
  gtk_widget_show (label176);
  gtk_box_pack_start (GTK_BOX (vbox46), label176, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label176), GTK_JUSTIFY_LEFT);

  spinbutton_talent_adj = gtk_adjustment_new (5, 1, 9.9, 0.1, 10, 10);
  spinbutton_talent = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_talent_adj), 0.1, 1);
  gtk_widget_show (spinbutton_talent);
  gtk_box_pack_start (GTK_BOX (vbox46), spinbutton_talent, FALSE, FALSE, 3);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_talent), TRUE);

  vbox47 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox47);
  gtk_box_pack_start (GTK_BOX (hbox94), vbox47, TRUE, TRUE, 0);

  label177 = gtk_label_new (_("Birth year and month"));
  gtk_widget_show (label177);
  gtk_box_pack_start (GTK_BOX (vbox47), label177, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label177), GTK_JUSTIFY_LEFT);

  hbox97 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox97);
  gtk_box_pack_start (GTK_BOX (vbox47), hbox97, FALSE, FALSE, 3);

  spinbutton_birth_year_adj = gtk_adjustment_new (1980, 1930, 2030, 1, 10, 10);
  spinbutton_birth_year = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_birth_year_adj), 1, 0);
  gtk_widget_show (spinbutton_birth_year);
  gtk_box_pack_start (GTK_BOX (hbox97), spinbutton_birth_year, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_birth_year), TRUE);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (spinbutton_birth_year), TRUE);

  spinbutton_birth_month_adj = gtk_adjustment_new (6, 1, 12, 1, 10, 10);
  spinbutton_birth_month = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_birth_month_adj), 1, 0);
  gtk_widget_show (spinbutton_birth_month);
  gtk_box_pack_start (GTK_BOX (hbox97), spinbutton_birth_month, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_birth_month), TRUE);

  button_update = gtk_button_new ();
  gtk_widget_show (button_update);
  gtk_box_pack_start (GTK_BOX (hbox94), button_update, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_update), 3);
  gtk_tooltips_set_tip (tooltips, button_update, _("Update player information"), NULL);
  gtk_widget_add_accelerator (button_update, "clicked", accel_group,
                              GDK_Return, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image72 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image72);
  gtk_container_add (GTK_CONTAINER (button_update), image72);

  button_prev = gtk_button_new ();
  gtk_widget_show (button_prev);
  gtk_box_pack_start (GTK_BOX (hbox94), button_prev, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_prev), 3);
  gtk_tooltips_set_tip (tooltips, button_prev, _("Select previous player (Ctrl-Left)"), NULL);
  gtk_widget_add_accelerator (button_prev, "clicked", accel_group,
                              GDK_Left, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image77 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image77);
  gtk_container_add (GTK_CONTAINER (button_prev), image77);

  button_next = gtk_button_new ();
  gtk_widget_show (button_next);
  gtk_box_pack_start (GTK_BOX (hbox94), button_next, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_next), 3);
  gtk_tooltips_set_tip (tooltips, button_next, _("Select next player (Ctrl-Right)"), NULL);
  gtk_widget_add_accelerator (button_next, "clicked", accel_group,
                              GDK_Right, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image78 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image78);
  gtk_container_add (GTK_CONTAINER (button_next), image78);

  hseparator15 = gtk_hseparator_new ();
  gtk_widget_show (hseparator15);
  gtk_box_pack_start (GTK_BOX (vbox36), hseparator15, FALSE, FALSE, 0);
  gtk_widget_set_size_request (hseparator15, 1, 10);

  hbox87 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox87);
  gtk_box_pack_start (GTK_BOX (vbox36), hbox87, FALSE, FALSE, 0);

  hbox84 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox84);
  gtk_box_pack_start (GTK_BOX (hbox87), hbox84, FALSE, TRUE, 5);

  label137 = gtk_label_new (_("Swap two players   "));
  gtk_widget_show (label137);
  gtk_box_pack_start (GTK_BOX (hbox84), label137, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label137), GTK_JUSTIFY_LEFT);

  spinbutton_swap1_adj = gtk_adjustment_new (1, 1, 20, 1, 10, 10);
  spinbutton_swap1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_swap1_adj), 1, 0);
  gtk_widget_show (spinbutton_swap1);
  gtk_box_pack_start (GTK_BOX (hbox84), spinbutton_swap1, FALSE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_swap1), TRUE);

  button_swap = gtk_button_new ();
  gtk_widget_show (button_swap);
  gtk_box_pack_start (GTK_BOX (hbox84), button_swap, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_swap), 3);
  gtk_tooltips_set_tip (tooltips, button_swap, _("Swap players"), NULL);

  image66 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image66);
  gtk_container_add (GTK_CONTAINER (button_swap), image66);

  spinbutton_swap2_adj = gtk_adjustment_new (2, 1, 20, 1, 10, 10);
  spinbutton_swap2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_swap2_adj), 1, 0);
  gtk_widget_show (spinbutton_swap2);
  gtk_box_pack_start (GTK_BOX (hbox84), spinbutton_swap2, FALSE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_swap2), TRUE);

  hbox88 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox88);
  gtk_box_pack_start (GTK_BOX (hbox87), hbox88, TRUE, TRUE, 5);

  label171 = gtk_label_new (_("  Move player"));
  gtk_widget_show (label171);
  gtk_box_pack_start (GTK_BOX (hbox88), label171, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label171), GTK_JUSTIFY_LEFT);

  spinbutton_move_adj = gtk_adjustment_new (1, 1, 20, 1, 10, 10);
  spinbutton_move = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_move_adj), 1, 0);
  gtk_widget_show (spinbutton_move);
  gtk_box_pack_start (GTK_BOX (hbox88), spinbutton_move, FALSE, TRUE, 3);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_move), TRUE);

  button_up = gtk_button_new ();
  gtk_widget_show (button_up);
  gtk_box_pack_start (GTK_BOX (hbox88), button_up, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_up), 3);
  gtk_tooltips_set_tip (tooltips, button_up, _("Move player up (Ctrl-Up)"), NULL);
  gtk_widget_add_accelerator (button_up, "clicked", accel_group,
                              GDK_Up, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button_up), alignment22);

  hbox89 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox89);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox89);

  image70 = gtk_image_new_from_stock ("gtk-go-up", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image70);
  gtk_box_pack_start (GTK_BOX (hbox89), image70, FALSE, FALSE, 0);

  label172 = gtk_label_new_with_mnemonic (_("Up"));
  gtk_widget_show (label172);
  gtk_box_pack_start (GTK_BOX (hbox89), label172, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label172), GTK_JUSTIFY_LEFT);

  button_down = gtk_button_new ();
  gtk_widget_show (button_down);
  gtk_box_pack_start (GTK_BOX (hbox88), button_down, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_down), 3);
  gtk_tooltips_set_tip (tooltips, button_down, _("Move player down (Ctrl-Down)"), NULL);
  gtk_widget_add_accelerator (button_down, "clicked", accel_group,
                              GDK_Down, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button_down), alignment23);

  hbox90 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox90);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox90);

  image71 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image71);
  gtk_box_pack_start (GTK_BOX (hbox90), image71, FALSE, FALSE, 0);

  label173 = gtk_label_new_with_mnemonic (_("Down"));
  gtk_widget_show (label173);
  gtk_box_pack_start (GTK_BOX (hbox90), label173, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label173), GTK_JUSTIFY_LEFT);

  hseparator19 = gtk_hseparator_new ();
  gtk_widget_show (hseparator19);
  gtk_box_pack_start (GTK_BOX (vbox36), hseparator19, FALSE, TRUE, 0);
  gtk_widget_set_size_request (hseparator19, 1, 10);

  hbox64 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox64);
  gtk_box_pack_start (GTK_BOX (vbox36), hbox64, FALSE, TRUE, 0);

  button_editor_help = gtk_button_new ();
  gtk_widget_show (button_editor_help);
  gtk_box_pack_start (GTK_BOX (hbox64), button_editor_help, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_editor_help), 3);
  gtk_tooltips_set_tip (tooltips, button_editor_help, _("Show editor help (F1)"), NULL);
  gtk_widget_add_accelerator (button_editor_help, "clicked", accel_group,
                              GDK_F1, 0,
                              GTK_ACCEL_VISIBLE);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button_editor_help), alignment25);

  hbox96 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox96);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox96);

  image74 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image74);
  gtk_box_pack_start (GTK_BOX (hbox96), image74, FALSE, FALSE, 0);

  label179 = gtk_label_new_with_mnemonic (_("Help"));
  gtk_widget_show (label179);
  gtk_box_pack_start (GTK_BOX (hbox96), label179, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label179), GTK_JUSTIFY_LEFT);

  button_exit = gtk_button_new ();
  gtk_widget_show (button_exit);
  gtk_box_pack_start (GTK_BOX (hbox64), button_exit, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_exit), 3);
  gtk_tooltips_set_tip (tooltips, button_exit, _("Quit (Esc)"), NULL);
  gtk_widget_add_accelerator (button_exit, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button_exit), alignment26);

  hbox99 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox99);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox99);

  image79 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image79);
  gtk_box_pack_start (GTK_BOX (hbox99), image79, FALSE, FALSE, 0);

  label184 = gtk_label_new_with_mnemonic (_("Quit"));
  gtk_widget_show (label184);
  gtk_box_pack_start (GTK_BOX (hbox99), label184, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label184), GTK_JUSTIFY_LEFT);

  button_save = gtk_button_new ();
  gtk_widget_show (button_save);
  gtk_box_pack_start (GTK_BOX (hbox64), button_save, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_save), 3);
  gtk_tooltips_set_tip (tooltips, button_save, _("Save current team to file (Ctrl-S)"), NULL);
  gtk_widget_add_accelerator (button_save, "clicked", accel_group,
                              GDK_s, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button_save), alignment18);

  hbox67 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox67);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox67);

  image61 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image61);
  gtk_box_pack_start (GTK_BOX (hbox67), image61, FALSE, FALSE, 0);

  label94 = gtk_label_new_with_mnemonic (_("Save"));
  gtk_widget_show (label94);
  gtk_box_pack_start (GTK_BOX (hbox67), label94, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label94), GTK_JUSTIFY_LEFT);

  button_import = gtk_button_new ();
  gtk_widget_show (button_import);
  gtk_box_pack_start (GTK_BOX (hbox64), button_import, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_import), 2);
  gtk_tooltips_set_tip (tooltips, button_import, _("Import teams from a definition file (the existing definition file will be expanded)"), NULL);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (button_import), alignment28);

  hbox101 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox101);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox101);

  image81 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image81);
  gtk_box_pack_start (GTK_BOX (hbox101), image81, FALSE, FALSE, 0);

  label186 = gtk_label_new_with_mnemonic (_("Import"));
  gtk_widget_show (label186);
  gtk_box_pack_start (GTK_BOX (hbox101), label186, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label186), GTK_JUSTIFY_LEFT);

  button_export = gtk_button_new ();
  gtk_widget_show (button_export);
  gtk_box_pack_start (GTK_BOX (hbox64), button_export, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_export), 2);
  gtk_tooltips_set_tip (tooltips, button_export, _("Export the current team to a file (which will be overwritten if it exists)"), NULL);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (button_export), alignment27);

  hbox100 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox100);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox100);

  image80 = gtk_image_new_from_stock ("gtk-floppy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image80);
  gtk_box_pack_start (GTK_BOX (hbox100), image80, FALSE, FALSE, 0);

  label185 = gtk_label_new_with_mnemonic (_("Export"));
  gtk_widget_show (label185);
  gtk_box_pack_start (GTK_BOX (hbox100), label185, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label185), GTK_JUSTIFY_LEFT);

  button_play_ws = gtk_button_new ();
  gtk_widget_show (button_play_ws);
  gtk_box_pack_start (GTK_BOX (hbox64), button_play_ws, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_play_ws), 3);
  gtk_tooltips_set_tip (tooltips, button_play_ws, _("Start Bygfoot without saving changes"), NULL);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button_play_ws), alignment24);

  hbox95 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox95);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox95);

  image73 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image73);
  gtk_box_pack_start (GTK_BOX (hbox95), image73, FALSE, FALSE, 0);

  label178 = gtk_label_new_with_mnemonic (_("Discard / Play"));
  gtk_widget_show (label178);
  gtk_box_pack_start (GTK_BOX (hbox95), label178, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label178), GTK_JUSTIFY_LEFT);

  button_save_play = gtk_button_new ();
  gtk_widget_show (button_save_play);
  gtk_box_pack_start (GTK_BOX (hbox64), button_save_play, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_save_play), 3);
  gtk_tooltips_set_tip (tooltips, button_save_play, _("Save team definition file and start Bygfoot"), NULL);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button_save_play), alignment21);

  hbox71 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox71);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox71);

  image65 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image65);
  gtk_box_pack_start (GTK_BOX (hbox71), image65, FALSE, FALSE, 0);

  label170 = gtk_label_new_with_mnemonic (_("Save / Play"));
  gtk_widget_show (label170);
  gtk_box_pack_start (GTK_BOX (hbox71), label170, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label170), GTK_JUSTIFY_LEFT);

  g_signal_connect ((gpointer) editor_window, "delete_event",
                    G_CALLBACK (on_button_exit_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_choose_def, "clicked",
                    G_CALLBACK (on_button_choose_def_clicked),
                    NULL);
  g_signal_connect ((gpointer) entry_country_file, "changed",
                    G_CALLBACK (on_entry_country_file_changed),
                    NULL);
  g_signal_connect ((gpointer) button_browse_team_files, "clicked",
                    G_CALLBACK (on_button_browse_team_files_clicked),
                    NULL);
  g_signal_connect ((gpointer) entry_team, "changed",
                    G_CALLBACK (on_entry_team_changed),
                    NULL);
  g_signal_connect ((gpointer) entry_structure1, "activate",
                    G_CALLBACK (on_button_change_structures_clicked),
                    NULL);
  g_signal_connect ((gpointer) entry_structure2, "activate",
                    G_CALLBACK (on_button_change_structures_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_change_structures, "clicked",
                    G_CALLBACK (on_button_change_structures_clicked),
                    NULL);
  g_signal_connect ((gpointer) spinbutton_average_skill, "value_changed",
                    G_CALLBACK (on_spinbutton_average_skill_value_changed),
                    NULL);
  g_signal_connect ((gpointer) treeview_players, "button_press_event",
                    G_CALLBACK (on_treeview_players_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) entry_name, "activate",
                    G_CALLBACK (on_button_update_clicked),
                    NULL);
  g_signal_connect ((gpointer) spinbutton_skill, "activate",
                    G_CALLBACK (on_button_update_clicked),
                    NULL);
  g_signal_connect ((gpointer) spinbutton_talent, "activate",
                    G_CALLBACK (on_button_update_clicked),
                    NULL);
  g_signal_connect ((gpointer) spinbutton_birth_year, "activate",
                    G_CALLBACK (on_button_update_clicked),
                    NULL);
  g_signal_connect ((gpointer) spinbutton_birth_month, "activate",
                    G_CALLBACK (on_button_update_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_update, "clicked",
                    G_CALLBACK (on_button_update_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_prev, "clicked",
                    G_CALLBACK (on_button_prev_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_next, "clicked",
                    G_CALLBACK (on_button_next_clicked),
                    NULL);
  g_signal_connect ((gpointer) spinbutton_swap1, "activate",
                    G_CALLBACK (on_button_swap_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_swap, "clicked",
                    G_CALLBACK (on_button_swap_clicked),
                    NULL);
  g_signal_connect ((gpointer) spinbutton_swap2, "activate",
                    G_CALLBACK (on_button_swap_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_up, "clicked",
                    G_CALLBACK (on_button_up_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_down, "clicked",
                    G_CALLBACK (on_button_down_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_editor_help, "clicked",
                    G_CALLBACK (on_button_editor_help_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_exit, "clicked",
                    G_CALLBACK (on_button_exit_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_save, "clicked",
                    G_CALLBACK (on_button_save_defs_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_import, "clicked",
                    G_CALLBACK (on_button_import_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_export, "clicked",
                    G_CALLBACK (on_button_export_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_play_ws, "clicked",
                    G_CALLBACK (on_button_play_ws_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_save_play, "clicked",
                    G_CALLBACK (on_button_save_play_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (editor_window, editor_window, "editor_window");
  GLADE_HOOKUP_OBJECT (editor_window, vbox36, "vbox36");
  GLADE_HOOKUP_OBJECT (editor_window, hbox86, "hbox86");
  GLADE_HOOKUP_OBJECT (editor_window, vbox42, "vbox42");
  GLADE_HOOKUP_OBJECT (editor_window, label138, "label138");
  GLADE_HOOKUP_OBJECT (editor_window, entry_definitions_file, "entry_definitions_file");
  GLADE_HOOKUP_OBJECT (editor_window, button_choose_def, "button_choose_def");
  GLADE_HOOKUP_OBJECT (editor_window, image68, "image68");
  GLADE_HOOKUP_OBJECT (editor_window, hbox50, "hbox50");
  GLADE_HOOKUP_OBJECT (editor_window, vbox37, "vbox37");
  GLADE_HOOKUP_OBJECT (editor_window, label73, "label73");
  GLADE_HOOKUP_OBJECT (editor_window, combo_team_file, "combo_team_file");
  GLADE_HOOKUP_OBJECT (editor_window, entry_country_file, "entry_country_file");
  GLADE_HOOKUP_OBJECT (editor_window, button_browse_team_files, "button_browse_team_files");
  GLADE_HOOKUP_OBJECT (editor_window, image56, "image56");
  GLADE_HOOKUP_OBJECT (editor_window, hseparator16, "hseparator16");
  GLADE_HOOKUP_OBJECT (editor_window, hbox69, "hbox69");
  GLADE_HOOKUP_OBJECT (editor_window, vbox38, "vbox38");
  GLADE_HOOKUP_OBJECT (editor_window, label75, "label75");
  GLADE_HOOKUP_OBJECT (editor_window, hbox51, "hbox51");
  GLADE_HOOKUP_OBJECT (editor_window, combo_team_names, "combo_team_names");
  GLADE_HOOKUP_OBJECT (editor_window, entry_team, "entry_team");
  GLADE_HOOKUP_OBJECT (editor_window, eventbox2, "eventbox2");
  GLADE_HOOKUP_OBJECT (editor_window, hbox98, "hbox98");
  GLADE_HOOKUP_OBJECT (editor_window, label183, "label183");
  GLADE_HOOKUP_OBJECT (editor_window, entry_team_name, "entry_team_name");
  GLADE_HOOKUP_OBJECT (editor_window, vseparator123, "vseparator123");
  GLADE_HOOKUP_OBJECT (editor_window, vbox41, "vbox41");
  GLADE_HOOKUP_OBJECT (editor_window, label_structures, "label_structures");
  GLADE_HOOKUP_OBJECT (editor_window, hbox85, "hbox85");
  GLADE_HOOKUP_OBJECT (editor_window, entry_structure1, "entry_structure1");
  GLADE_HOOKUP_OBJECT (editor_window, entry_structure2, "entry_structure2");
  GLADE_HOOKUP_OBJECT (editor_window, button_change_structures, "button_change_structures");
  GLADE_HOOKUP_OBJECT (editor_window, image63, "image63");
  GLADE_HOOKUP_OBJECT (editor_window, vseparator124, "vseparator124");
  GLADE_HOOKUP_OBJECT (editor_window, vbox49, "vbox49");
  GLADE_HOOKUP_OBJECT (editor_window, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (editor_window, vbox50, "vbox50");
  GLADE_HOOKUP_OBJECT (editor_window, label182, "label182");
  GLADE_HOOKUP_OBJECT (editor_window, spinbutton_average_skill, "spinbutton_average_skill");
  GLADE_HOOKUP_OBJECT (editor_window, hseparator13, "hseparator13");
  GLADE_HOOKUP_OBJECT (editor_window, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (editor_window, treeview_players, "treeview_players");
  GLADE_HOOKUP_OBJECT (editor_window, hbox94, "hbox94");
  GLADE_HOOKUP_OBJECT (editor_window, vbox48, "vbox48");
  GLADE_HOOKUP_OBJECT (editor_window, label181, "label181");
  GLADE_HOOKUP_OBJECT (editor_window, label_number, "label_number");
  GLADE_HOOKUP_OBJECT (editor_window, vbox44, "vbox44");
  GLADE_HOOKUP_OBJECT (editor_window, label174, "label174");
  GLADE_HOOKUP_OBJECT (editor_window, entry_name, "entry_name");
  GLADE_HOOKUP_OBJECT (editor_window, vbox45, "vbox45");
  GLADE_HOOKUP_OBJECT (editor_window, label175, "label175");
  GLADE_HOOKUP_OBJECT (editor_window, spinbutton_skill, "spinbutton_skill");
  GLADE_HOOKUP_OBJECT (editor_window, vbox46, "vbox46");
  GLADE_HOOKUP_OBJECT (editor_window, label176, "label176");
  GLADE_HOOKUP_OBJECT (editor_window, spinbutton_talent, "spinbutton_talent");
  GLADE_HOOKUP_OBJECT (editor_window, vbox47, "vbox47");
  GLADE_HOOKUP_OBJECT (editor_window, label177, "label177");
  GLADE_HOOKUP_OBJECT (editor_window, hbox97, "hbox97");
  GLADE_HOOKUP_OBJECT (editor_window, spinbutton_birth_year, "spinbutton_birth_year");
  GLADE_HOOKUP_OBJECT (editor_window, spinbutton_birth_month, "spinbutton_birth_month");
  GLADE_HOOKUP_OBJECT (editor_window, button_update, "button_update");
  GLADE_HOOKUP_OBJECT (editor_window, image72, "image72");
  GLADE_HOOKUP_OBJECT (editor_window, button_prev, "button_prev");
  GLADE_HOOKUP_OBJECT (editor_window, image77, "image77");
  GLADE_HOOKUP_OBJECT (editor_window, button_next, "button_next");
  GLADE_HOOKUP_OBJECT (editor_window, image78, "image78");
  GLADE_HOOKUP_OBJECT (editor_window, hseparator15, "hseparator15");
  GLADE_HOOKUP_OBJECT (editor_window, hbox87, "hbox87");
  GLADE_HOOKUP_OBJECT (editor_window, hbox84, "hbox84");
  GLADE_HOOKUP_OBJECT (editor_window, label137, "label137");
  GLADE_HOOKUP_OBJECT (editor_window, spinbutton_swap1, "spinbutton_swap1");
  GLADE_HOOKUP_OBJECT (editor_window, button_swap, "button_swap");
  GLADE_HOOKUP_OBJECT (editor_window, image66, "image66");
  GLADE_HOOKUP_OBJECT (editor_window, spinbutton_swap2, "spinbutton_swap2");
  GLADE_HOOKUP_OBJECT (editor_window, hbox88, "hbox88");
  GLADE_HOOKUP_OBJECT (editor_window, label171, "label171");
  GLADE_HOOKUP_OBJECT (editor_window, spinbutton_move, "spinbutton_move");
  GLADE_HOOKUP_OBJECT (editor_window, button_up, "button_up");
  GLADE_HOOKUP_OBJECT (editor_window, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (editor_window, hbox89, "hbox89");
  GLADE_HOOKUP_OBJECT (editor_window, image70, "image70");
  GLADE_HOOKUP_OBJECT (editor_window, label172, "label172");
  GLADE_HOOKUP_OBJECT (editor_window, button_down, "button_down");
  GLADE_HOOKUP_OBJECT (editor_window, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (editor_window, hbox90, "hbox90");
  GLADE_HOOKUP_OBJECT (editor_window, image71, "image71");
  GLADE_HOOKUP_OBJECT (editor_window, label173, "label173");
  GLADE_HOOKUP_OBJECT (editor_window, hseparator19, "hseparator19");
  GLADE_HOOKUP_OBJECT (editor_window, hbox64, "hbox64");
  GLADE_HOOKUP_OBJECT (editor_window, button_editor_help, "button_editor_help");
  GLADE_HOOKUP_OBJECT (editor_window, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (editor_window, hbox96, "hbox96");
  GLADE_HOOKUP_OBJECT (editor_window, image74, "image74");
  GLADE_HOOKUP_OBJECT (editor_window, label179, "label179");
  GLADE_HOOKUP_OBJECT (editor_window, button_exit, "button_exit");
  GLADE_HOOKUP_OBJECT (editor_window, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (editor_window, hbox99, "hbox99");
  GLADE_HOOKUP_OBJECT (editor_window, image79, "image79");
  GLADE_HOOKUP_OBJECT (editor_window, label184, "label184");
  GLADE_HOOKUP_OBJECT (editor_window, button_save, "button_save");
  GLADE_HOOKUP_OBJECT (editor_window, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (editor_window, hbox67, "hbox67");
  GLADE_HOOKUP_OBJECT (editor_window, image61, "image61");
  GLADE_HOOKUP_OBJECT (editor_window, label94, "label94");
  GLADE_HOOKUP_OBJECT (editor_window, button_import, "button_import");
  GLADE_HOOKUP_OBJECT (editor_window, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (editor_window, hbox101, "hbox101");
  GLADE_HOOKUP_OBJECT (editor_window, image81, "image81");
  GLADE_HOOKUP_OBJECT (editor_window, label186, "label186");
  GLADE_HOOKUP_OBJECT (editor_window, button_export, "button_export");
  GLADE_HOOKUP_OBJECT (editor_window, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (editor_window, hbox100, "hbox100");
  GLADE_HOOKUP_OBJECT (editor_window, image80, "image80");
  GLADE_HOOKUP_OBJECT (editor_window, label185, "label185");
  GLADE_HOOKUP_OBJECT (editor_window, button_play_ws, "button_play_ws");
  GLADE_HOOKUP_OBJECT (editor_window, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (editor_window, hbox95, "hbox95");
  GLADE_HOOKUP_OBJECT (editor_window, image73, "image73");
  GLADE_HOOKUP_OBJECT (editor_window, label178, "label178");
  GLADE_HOOKUP_OBJECT (editor_window, button_save_play, "button_save_play");
  GLADE_HOOKUP_OBJECT (editor_window, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (editor_window, hbox71, "hbox71");
  GLADE_HOOKUP_OBJECT (editor_window, image65, "image65");
  GLADE_HOOKUP_OBJECT (editor_window, label170, "label170");
  GLADE_HOOKUP_OBJECT_NO_REF (editor_window, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (editor_window), accel_group);

  return editor_window;
}

