/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_job_offer (void);
GtkWidget* create_window_progress (void);
GtkWidget* create_window_warning (void);
GtkWidget* create_window_digits (void);
GtkWidget* create_window_yesno (void);
