/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#include "bygfoot_struct.h"

GtkWidget* create_window_bets (void);
GtkWidget* create_window_splash (Bygfoot *bygfoot);
GtkWidget* create_window_alr (void);
GtkWidget* create_window_news (void);
GtkWidget* create_window_network_select (Bygfoot *bygfoot);
