/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_startup (void);
GtkWidget* create_fsel_window (void);
GtkWidget* create_window_font_sel (void);
GtkWidget* create_window_live (void);
GtkWidget* create_help_window (void);
GtkWidget* create_window_stadium (void);
