/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_stadium_window (void);
GtkWidget* create_job_offer_window (void);
GtkWidget* create_graph_window (void);
GtkWidget* create_window_progress (void);
GtkWidget* create_window_warning (void);
