/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "misc_callbacks.h"
#include "misc_interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_startup (void)
{
  GtkWidget *window_startup;
  GtkWidget *vbox2;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview_startup;
  GtkWidget *hseparator10;
  GtkWidget *label4;
  GtkWidget *eventbox1;
  GtkWidget *hbox2;
  GtkWidget *team_selection_radio1;
  GSList *team_selection_radio1_group = NULL;
  GtkWidget *team_selection_radio2;
  GtkWidget *team_selection_radio3;
  GtkWidget *hseparator11;
  GtkWidget *vbox34;
  GtkWidget *label69;
  GtkWidget *hbox44;
  GtkWidget *combo_country;
  GtkWidget *combo_country_entry;
  GtkWidget *vseparator17;
  GtkWidget *button_select_country_file;
  GtkWidget *alignment14;
  GtkWidget *hbox45;
  GtkWidget *image45;
  GtkWidget *label70;
  GtkWidget *hseparator12;
  GtkWidget *hbox46;
  GtkWidget *vbox35;
  GtkWidget *checkbutton_no_def;
  GtkWidget *checkbutton_only_names;
  GtkWidget *checkbutton_load_my_team;
  GtkWidget *vseparator18;
  GtkWidget *button_start_editor;
  GtkWidget *alignment15;
  GtkWidget *hbox47;
  GtkWidget *image55;
  GtkWidget *label71;
  GtkWidget *hbox3;
  GtkWidget *team_selection_ok;
  GtkWidget *alignment1;
  GtkWidget *hbox4;
  GtkWidget *image2;
  GtkWidget *label1;
  GtkWidget *team_selection_cancel;
  GtkWidget *alignment2;
  GtkWidget *hbox5;
  GtkWidget *image3;
  GtkWidget *label2;
  GtkWidget *team_selection_load;
  GtkWidget *alignment3;
  GtkWidget *hbox6;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  window_startup = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (window_startup), 6);
  gtk_window_set_title (GTK_WINDOW (window_startup), _("Select team and country"));
  gtk_window_set_position (GTK_WINDOW (window_startup), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window_startup), 500, 600);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (window_startup), vbox2);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow1), 6);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  treeview_startup = gtk_tree_view_new ();
  gtk_widget_show (treeview_startup);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview_startup);
  gtk_container_set_border_width (GTK_CONTAINER (treeview_startup), 2);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview_startup), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (treeview_startup), TRUE);

  hseparator10 = gtk_hseparator_new ();
  gtk_widget_show (hseparator10);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator10, FALSE, FALSE, 0);
  gtk_widget_set_size_request (hseparator10, 1, 10);

  label4 = gtk_label_new (_("Start in"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (vbox2), label4, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0.05, 0.5);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), eventbox1, FALSE, TRUE, 5);
  gtk_tooltips_set_tip (tooltips, eventbox1, _("Play normal league games and cups"), NULL);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (eventbox1), hbox2);

  team_selection_radio1 = gtk_radio_button_new_with_mnemonic (NULL, _("Top league"));
  gtk_widget_show (team_selection_radio1);
  gtk_box_pack_start (GTK_BOX (hbox2), team_selection_radio1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (team_selection_radio1), 3);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (team_selection_radio1), team_selection_radio1_group);
  team_selection_radio1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (team_selection_radio1));

  team_selection_radio2 = gtk_radio_button_new_with_mnemonic (NULL, _("Current league"));
  gtk_widget_show (team_selection_radio2);
  gtk_box_pack_start (GTK_BOX (hbox2), team_selection_radio2, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (team_selection_radio2), 3);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (team_selection_radio2), team_selection_radio1_group);
  team_selection_radio1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (team_selection_radio2));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (team_selection_radio2), TRUE);

  team_selection_radio3 = gtk_radio_button_new_with_mnemonic (NULL, _("Bottom league"));
  gtk_widget_show (team_selection_radio3);
  gtk_box_pack_start (GTK_BOX (hbox2), team_selection_radio3, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (team_selection_radio3), 3);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (team_selection_radio3), team_selection_radio1_group);
  team_selection_radio1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (team_selection_radio3));

  hseparator11 = gtk_hseparator_new ();
  gtk_widget_show (hseparator11);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator11, FALSE, FALSE, 0);
  gtk_widget_set_size_request (hseparator11, 1, 10);

  vbox34 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox34);
  gtk_box_pack_start (GTK_BOX (vbox2), vbox34, FALSE, TRUE, 5);

  label69 = gtk_label_new (_("Choose country"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (vbox34), label69, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label69), 0.05, 0.5);
  gtk_misc_set_padding (GTK_MISC (label69), 0, 5);

  hbox44 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox44);
  gtk_box_pack_start (GTK_BOX (vbox34), hbox44, TRUE, TRUE, 0);

  combo_country = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_country)->popwin),
                     "GladeParentKey", combo_country);
  gtk_widget_show (combo_country);
  gtk_box_pack_start (GTK_BOX (hbox44), combo_country, FALSE, TRUE, 0);

  combo_country_entry = GTK_COMBO (combo_country)->entry;
  gtk_widget_show (combo_country_entry);

  vseparator17 = gtk_vseparator_new ();
  gtk_widget_show (vseparator17);
  gtk_box_pack_start (GTK_BOX (hbox44), vseparator17, FALSE, FALSE, 0);
  gtk_widget_set_size_request (vseparator17, 15, 1);

  button_select_country_file = gtk_button_new ();
  gtk_widget_show (button_select_country_file);
  gtk_box_pack_start (GTK_BOX (hbox44), button_select_country_file, TRUE, TRUE, 2);
  gtk_tooltips_set_tip (tooltips, button_select_country_file, _("Choose a custom country file (see Help)"), NULL);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_select_country_file), alignment14);

  hbox45 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox45);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox45);

  image45 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image45);
  gtk_box_pack_start (GTK_BOX (hbox45), image45, FALSE, FALSE, 0);

  label70 = gtk_label_new_with_mnemonic (_("Select a country file"));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox45), label70, FALSE, FALSE, 0);

  hseparator12 = gtk_hseparator_new ();
  gtk_widget_show (hseparator12);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator12, FALSE, FALSE, 0);
  gtk_widget_set_size_request (hseparator12, 1, 10);

  hbox46 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox46);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox46, FALSE, TRUE, 0);

  vbox35 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox35);
  gtk_box_pack_start (GTK_BOX (hbox46), vbox35, FALSE, TRUE, 0);

  checkbutton_no_def = gtk_check_button_new_with_mnemonic (_("Don't load team definitions"));
  gtk_widget_show (checkbutton_no_def);
  gtk_box_pack_start (GTK_BOX (vbox35), checkbutton_no_def, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton_no_def), 2);
  gtk_tooltips_set_tip (tooltips, checkbutton_no_def, _("If you check this, the game generates all players randomly and won't read the file with team definitions"), NULL);

  checkbutton_only_names = gtk_check_button_new_with_mnemonic (_("Load only names from team definition file"));
  gtk_widget_show (checkbutton_only_names);
  gtk_box_pack_start (GTK_BOX (vbox35), checkbutton_only_names, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton_only_names), 2);
  gtk_tooltips_set_tip (tooltips, checkbutton_only_names, _("If you check this, only the player names and the team structures are loaded from the definition file, values like skill or age are generated randomly"), NULL);

  checkbutton_load_my_team = gtk_check_button_new_with_mnemonic (_("Load my team from definitions file"));
  gtk_widget_show (checkbutton_load_my_team);
  gtk_box_pack_start (GTK_BOX (vbox35), checkbutton_load_my_team, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton_load_my_team), 2);
  gtk_tooltips_set_tip (tooltips, checkbutton_load_my_team, _("Check this if you'd like to have your team loaded from the definitions file no matter what the other checkbuttons say."), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_load_my_team), TRUE);

  vseparator18 = gtk_vseparator_new ();
  gtk_widget_show (vseparator18);
  gtk_box_pack_start (GTK_BOX (hbox46), vseparator18, FALSE, TRUE, 0);
  gtk_widget_set_size_request (vseparator18, 10, 1);

  button_start_editor = gtk_button_new ();
  gtk_widget_show (button_start_editor);
  gtk_box_pack_start (GTK_BOX (hbox46), button_start_editor, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_start_editor), 3);
  gtk_tooltips_set_tip (tooltips, button_start_editor, _("You can start the editor from the commandline with 'bygfoot -e' or '--editor'"), NULL);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_start_editor), alignment15);

  hbox47 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox47);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox47);

  image55 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image55);
  gtk_box_pack_start (GTK_BOX (hbox47), image55, FALSE, FALSE, 0);

  label71 = gtk_label_new_with_mnemonic (_("Start Bygfoot Team Editor"));
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox47), label71, FALSE, FALSE, 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox3, FALSE, TRUE, 0);

  team_selection_ok = gtk_button_new ();
  gtk_widget_show (team_selection_ok);
  gtk_box_pack_start (GTK_BOX (hbox3), team_selection_ok, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (team_selection_ok), 2);
  gtk_tooltips_set_tip (tooltips, team_selection_ok, _("Return"), NULL);
  gtk_widget_add_accelerator (team_selection_ok, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (team_selection_ok), alignment1);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox4);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox4), image2, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox4), label1, FALSE, FALSE, 0);

  team_selection_cancel = gtk_button_new ();
  gtk_widget_show (team_selection_cancel);
  gtk_box_pack_start (GTK_BOX (hbox3), team_selection_cancel, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (team_selection_cancel), 2);
  gtk_tooltips_set_tip (tooltips, team_selection_cancel, _("Esc"), NULL);
  gtk_widget_add_accelerator (team_selection_cancel, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (team_selection_cancel), alignment2);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox5);

  image3 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox5), image3, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox5), label2, FALSE, FALSE, 0);

  team_selection_load = gtk_button_new ();
  gtk_widget_show (team_selection_load);
  gtk_box_pack_start (GTK_BOX (hbox3), team_selection_load, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (team_selection_load), 2);
  gtk_tooltips_set_tip (tooltips, team_selection_load, _("L"), NULL);
  gtk_widget_add_accelerator (team_selection_load, "clicked", accel_group,
                              GDK_l, 0,
                              GTK_ACCEL_VISIBLE);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (team_selection_load), alignment3);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox6);

  image4 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox6), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Load game"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox6), label5, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) window_startup, "delete_event",
                    G_CALLBACK (on_team_selection_cancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_startup, "row_activated",
                    G_CALLBACK (on_team_selection_tv_row_activated),
                    NULL);
  g_signal_connect ((gpointer) combo_country_entry, "changed",
                    G_CALLBACK (on_combo_country_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) button_select_country_file, "clicked",
                    G_CALLBACK (on_button_select_country_file_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_no_def, "toggled",
                    G_CALLBACK (on_checkbutton_load_randomly_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_only_names, "toggled",
                    G_CALLBACK (on_checkbutton_only_names_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_start_editor, "clicked",
                    G_CALLBACK (on_button_start_editor_clicked),
                    NULL);
  g_signal_connect ((gpointer) team_selection_ok, "clicked",
                    G_CALLBACK (on_team_selection_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) team_selection_cancel, "clicked",
                    G_CALLBACK (on_team_selection_cancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) team_selection_load, "clicked",
                    G_CALLBACK (on_team_selection_load_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_startup, window_startup, "window_startup");
  GLADE_HOOKUP_OBJECT (window_startup, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (window_startup, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window_startup, treeview_startup, "treeview_startup");
  GLADE_HOOKUP_OBJECT (window_startup, hseparator10, "hseparator10");
  GLADE_HOOKUP_OBJECT (window_startup, label4, "label4");
  GLADE_HOOKUP_OBJECT (window_startup, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (window_startup, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window_startup, team_selection_radio1, "team_selection_radio1");
  GLADE_HOOKUP_OBJECT (window_startup, team_selection_radio2, "team_selection_radio2");
  GLADE_HOOKUP_OBJECT (window_startup, team_selection_radio3, "team_selection_radio3");
  GLADE_HOOKUP_OBJECT (window_startup, hseparator11, "hseparator11");
  GLADE_HOOKUP_OBJECT (window_startup, vbox34, "vbox34");
  GLADE_HOOKUP_OBJECT (window_startup, label69, "label69");
  GLADE_HOOKUP_OBJECT (window_startup, hbox44, "hbox44");
  GLADE_HOOKUP_OBJECT (window_startup, combo_country, "combo_country");
  GLADE_HOOKUP_OBJECT (window_startup, combo_country_entry, "combo_country_entry");
  GLADE_HOOKUP_OBJECT (window_startup, vseparator17, "vseparator17");
  GLADE_HOOKUP_OBJECT (window_startup, button_select_country_file, "button_select_country_file");
  GLADE_HOOKUP_OBJECT (window_startup, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window_startup, hbox45, "hbox45");
  GLADE_HOOKUP_OBJECT (window_startup, image45, "image45");
  GLADE_HOOKUP_OBJECT (window_startup, label70, "label70");
  GLADE_HOOKUP_OBJECT (window_startup, hseparator12, "hseparator12");
  GLADE_HOOKUP_OBJECT (window_startup, hbox46, "hbox46");
  GLADE_HOOKUP_OBJECT (window_startup, vbox35, "vbox35");
  GLADE_HOOKUP_OBJECT (window_startup, checkbutton_no_def, "checkbutton_no_def");
  GLADE_HOOKUP_OBJECT (window_startup, checkbutton_only_names, "checkbutton_only_names");
  GLADE_HOOKUP_OBJECT (window_startup, checkbutton_load_my_team, "checkbutton_load_my_team");
  GLADE_HOOKUP_OBJECT (window_startup, vseparator18, "vseparator18");
  GLADE_HOOKUP_OBJECT (window_startup, button_start_editor, "button_start_editor");
  GLADE_HOOKUP_OBJECT (window_startup, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window_startup, hbox47, "hbox47");
  GLADE_HOOKUP_OBJECT (window_startup, image55, "image55");
  GLADE_HOOKUP_OBJECT (window_startup, label71, "label71");
  GLADE_HOOKUP_OBJECT (window_startup, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window_startup, team_selection_ok, "team_selection_ok");
  GLADE_HOOKUP_OBJECT (window_startup, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window_startup, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window_startup, image2, "image2");
  GLADE_HOOKUP_OBJECT (window_startup, label1, "label1");
  GLADE_HOOKUP_OBJECT (window_startup, team_selection_cancel, "team_selection_cancel");
  GLADE_HOOKUP_OBJECT (window_startup, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window_startup, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window_startup, image3, "image3");
  GLADE_HOOKUP_OBJECT (window_startup, label2, "label2");
  GLADE_HOOKUP_OBJECT (window_startup, team_selection_load, "team_selection_load");
  GLADE_HOOKUP_OBJECT (window_startup, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window_startup, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window_startup, image4, "image4");
  GLADE_HOOKUP_OBJECT (window_startup, label5, "label5");
  GLADE_HOOKUP_OBJECT_NO_REF (window_startup, tooltips, "tooltips");

  gtk_widget_grab_focus (treeview_startup);
  gtk_window_add_accel_group (GTK_WINDOW (window_startup), accel_group);

  return window_startup;
}

GtkWidget*
create_popup_window (void)
{
  GtkWidget *popup_window;
  GtkWidget *vbox12;
  GtkWidget *hbox16;
  GtkWidget *label_popup_status;
  GtkWidget *vseparator12;
  GtkWidget *label_popup_status2;
  GtkWidget *vseparator13;
  GtkWidget *label_popup_status3;
  GtkWidget *hbox20;
  GtkWidget *image_popup_warning;
  GtkWidget *image_popup_question;
  GtkWidget *label_popup_text;
  GtkWidget *radiobutton0;
  GSList *radiobutton0_group = NULL;
  GtkWidget *radiobutton1;
  GtkWidget *check_popup;
  GtkWidget *hbox17;
  GtkWidget *button_popup_ok;
  GtkWidget *alignment6;
  GtkWidget *hbox30;
  GtkWidget *image27;
  GtkWidget *label50;
  GtkWidget *button_popup_cancel;
  GtkWidget *alignment7;
  GtkWidget *hbox31;
  GtkWidget *image28;
  GtkWidget *label51;
  GtkWidget *button_popup_close;
  GtkWidget *alignment8;
  GtkWidget *hbox32;
  GtkWidget *image29;
  GtkWidget *label52;
  GtkWidget *button8;
  GtkWidget *button9;
  GtkWidget *button10;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  popup_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (popup_window), 6);
  gtk_window_set_title (GTK_WINDOW (popup_window), _("Bygfoot"));
  gtk_window_set_position (GTK_WINDOW (popup_window), GTK_WIN_POS_CENTER);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox12);
  gtk_container_add (GTK_CONTAINER (popup_window), vbox12);

  hbox16 = gtk_hbox_new (FALSE, 0);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox16, TRUE, TRUE, 0);

  label_popup_status = gtk_label_new (_("-1"));
  gtk_widget_show (label_popup_status);
  gtk_box_pack_start (GTK_BOX (hbox16), label_popup_status, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label_popup_status), 29, 0);

  vseparator12 = gtk_vseparator_new ();
  gtk_widget_show (vseparator12);
  gtk_box_pack_start (GTK_BOX (hbox16), vseparator12, TRUE, TRUE, 0);

  label_popup_status2 = gtk_label_new (_("-1"));
  gtk_widget_show (label_popup_status2);
  gtk_box_pack_start (GTK_BOX (hbox16), label_popup_status2, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label_popup_status2), 22, 0);

  vseparator13 = gtk_vseparator_new ();
  gtk_widget_show (vseparator13);
  gtk_box_pack_start (GTK_BOX (hbox16), vseparator13, TRUE, TRUE, 0);

  label_popup_status3 = gtk_label_new (_("-1"));
  gtk_widget_show (label_popup_status3);
  gtk_box_pack_start (GTK_BOX (hbox16), label_popup_status3, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label_popup_status3), 23, 0);

  hbox20 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox20);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox20, TRUE, TRUE, 0);

  image_popup_warning = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_DIALOG);
  gtk_box_pack_start (GTK_BOX (hbox20), image_popup_warning, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (image_popup_warning), 5, 5);

  image_popup_question = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_DIALOG);
  gtk_box_pack_start (GTK_BOX (hbox20), image_popup_question, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (image_popup_question), 5, 5);

  label_popup_text = gtk_label_new (_("label23"));
  gtk_widget_show (label_popup_text);
  gtk_box_pack_start (GTK_BOX (vbox12), label_popup_text, FALSE, FALSE, 10);
  gtk_label_set_line_wrap (GTK_LABEL (label_popup_text), TRUE);
  gtk_misc_set_padding (GTK_MISC (label_popup_text), 0, 6);

  radiobutton0 = gtk_radio_button_new_with_mnemonic (NULL, _("radiobutton0"));
  gtk_box_pack_start (GTK_BOX (vbox12), radiobutton0, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton0), radiobutton0_group);
  radiobutton0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton0));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton0), TRUE);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("radiobutton1"));
  gtk_box_pack_start (GTK_BOX (vbox12), radiobutton1, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton0_group);
  radiobutton0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  check_popup = gtk_check_button_new_with_mnemonic (_("Don't bother me with this next time"));
  gtk_box_pack_start (GTK_BOX (vbox12), check_popup, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (check_popup), 3);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox17);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox17, TRUE, TRUE, 0);

  button_popup_ok = gtk_button_new ();
  gtk_box_pack_start (GTK_BOX (hbox17), button_popup_ok, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_popup_ok), 2);
  gtk_tooltips_set_tip (tooltips, button_popup_ok, _("Return"), NULL);
  gtk_widget_add_accelerator (button_popup_ok, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_popup_ok), alignment6);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox30);

  image27 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox30), image27, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox30), label50, FALSE, FALSE, 0);

  button_popup_cancel = gtk_button_new ();
  gtk_box_pack_start (GTK_BOX (hbox17), button_popup_cancel, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_popup_cancel), 2);
  gtk_tooltips_set_tip (tooltips, button_popup_cancel, _("Esc"), NULL);
  gtk_widget_add_accelerator (button_popup_cancel, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_popup_cancel), alignment7);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox31);

  image28 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox31), image28, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox31), label51, FALSE, FALSE, 0);

  button_popup_close = gtk_button_new ();
  gtk_box_pack_start (GTK_BOX (hbox17), button_popup_close, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_popup_close), 2);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_popup_close), alignment8);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox32);

  image29 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox32), image29, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Close"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox32), label52, FALSE, FALSE, 0);

  button8 = gtk_button_new_with_mnemonic (_("button8"));
  gtk_box_pack_start (GTK_BOX (hbox17), button8, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button8), 2);

  button9 = gtk_button_new_with_mnemonic (_("button9"));
  gtk_box_pack_start (GTK_BOX (hbox17), button9, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button9), 2);

  button10 = gtk_button_new_with_mnemonic (_("button10"));
  gtk_box_pack_start (GTK_BOX (hbox17), button10, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button10), 2);

  g_signal_connect ((gpointer) popup_window, "delete_event",
                    G_CALLBACK (on_popup_window_delete_event),
                    NULL);
  g_signal_connect ((gpointer) check_popup, "toggled",
                    G_CALLBACK (on_popup_check_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_popup_ok, "clicked",
                    G_CALLBACK (on_button_popup_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_popup_cancel, "clicked",
                    G_CALLBACK (on_button_popup_cancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_popup_close, "clicked",
                    G_CALLBACK (on_button_popup_close_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (popup_window, popup_window, "popup_window");
  GLADE_HOOKUP_OBJECT (popup_window, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (popup_window, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (popup_window, label_popup_status, "label_popup_status");
  GLADE_HOOKUP_OBJECT (popup_window, vseparator12, "vseparator12");
  GLADE_HOOKUP_OBJECT (popup_window, label_popup_status2, "label_popup_status2");
  GLADE_HOOKUP_OBJECT (popup_window, vseparator13, "vseparator13");
  GLADE_HOOKUP_OBJECT (popup_window, label_popup_status3, "label_popup_status3");
  GLADE_HOOKUP_OBJECT (popup_window, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (popup_window, image_popup_warning, "image_popup_warning");
  GLADE_HOOKUP_OBJECT (popup_window, image_popup_question, "image_popup_question");
  GLADE_HOOKUP_OBJECT (popup_window, label_popup_text, "label_popup_text");
  GLADE_HOOKUP_OBJECT (popup_window, radiobutton0, "radiobutton0");
  GLADE_HOOKUP_OBJECT (popup_window, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (popup_window, check_popup, "check_popup");
  GLADE_HOOKUP_OBJECT (popup_window, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (popup_window, button_popup_ok, "button_popup_ok");
  GLADE_HOOKUP_OBJECT (popup_window, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (popup_window, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (popup_window, image27, "image27");
  GLADE_HOOKUP_OBJECT (popup_window, label50, "label50");
  GLADE_HOOKUP_OBJECT (popup_window, button_popup_cancel, "button_popup_cancel");
  GLADE_HOOKUP_OBJECT (popup_window, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (popup_window, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (popup_window, image28, "image28");
  GLADE_HOOKUP_OBJECT (popup_window, label51, "label51");
  GLADE_HOOKUP_OBJECT (popup_window, button_popup_close, "button_popup_close");
  GLADE_HOOKUP_OBJECT (popup_window, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (popup_window, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (popup_window, image29, "image29");
  GLADE_HOOKUP_OBJECT (popup_window, label52, "label52");
  GLADE_HOOKUP_OBJECT (popup_window, button8, "button8");
  GLADE_HOOKUP_OBJECT (popup_window, button9, "button9");
  GLADE_HOOKUP_OBJECT (popup_window, button10, "button10");
  GLADE_HOOKUP_OBJECT_NO_REF (popup_window, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (popup_window), accel_group);

  return popup_window;
}

GtkWidget*
create_fsel_window (void)
{
  GtkWidget *fsel_window;
  GtkWidget *button_fsel_ok;
  GtkWidget *button_fsel_cancel;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  fsel_window = gtk_file_selection_new (_("Choose file"));
  gtk_container_set_border_width (GTK_CONTAINER (fsel_window), 10);
  gtk_window_set_position (GTK_WINDOW (fsel_window), GTK_WIN_POS_CENTER);
  gtk_window_set_type_hint (GTK_WINDOW (fsel_window), GDK_WINDOW_TYPE_HINT_DIALOG);

  button_fsel_ok = GTK_FILE_SELECTION (fsel_window)->ok_button;
  gtk_widget_show (button_fsel_ok);
  GTK_WIDGET_SET_FLAGS (button_fsel_ok, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button_fsel_ok, _("Return"), NULL);
  gtk_widget_add_accelerator (button_fsel_ok, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  button_fsel_cancel = GTK_FILE_SELECTION (fsel_window)->cancel_button;
  gtk_widget_show (button_fsel_cancel);
  GTK_WIDGET_SET_FLAGS (button_fsel_cancel, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button_fsel_cancel, _("Esc"), NULL);
  gtk_widget_add_accelerator (button_fsel_cancel, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect ((gpointer) fsel_window, "delete_event",
                    G_CALLBACK (on_fsel_window_delete_event),
                    NULL);
  g_signal_connect ((gpointer) button_fsel_ok, "clicked",
                    G_CALLBACK (on_button_fsel_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_fsel_cancel, "clicked",
                    G_CALLBACK (on_button_fsel_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fsel_window, fsel_window, "fsel_window");
  GLADE_HOOKUP_OBJECT_NO_REF (fsel_window, button_fsel_ok, "button_fsel_ok");
  GLADE_HOOKUP_OBJECT_NO_REF (fsel_window, button_fsel_cancel, "button_fsel_cancel");
  GLADE_HOOKUP_OBJECT_NO_REF (fsel_window, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (fsel_window), accel_group);

  return fsel_window;
}

GtkWidget*
create_font_sel_window (void)
{
  GtkWidget *font_sel_window;
  GtkWidget *button_font_sel_ok;
  GtkWidget *button_font_sel_cancel;
  GtkWidget *button_font_sel_apply;
  GtkWidget *font_sel;

  font_sel_window = gtk_font_selection_dialog_new (_("Select font"));
  gtk_container_set_border_width (GTK_CONTAINER (font_sel_window), 6);
  gtk_window_set_position (GTK_WINDOW (font_sel_window), GTK_WIN_POS_CENTER);
  gtk_window_set_type_hint (GTK_WINDOW (font_sel_window), GDK_WINDOW_TYPE_HINT_DIALOG);

  button_font_sel_ok = GTK_FONT_SELECTION_DIALOG (font_sel_window)->ok_button;
  gtk_widget_show (button_font_sel_ok);
  GTK_WIDGET_SET_FLAGS (button_font_sel_ok, GTK_CAN_DEFAULT);

  button_font_sel_cancel = GTK_FONT_SELECTION_DIALOG (font_sel_window)->cancel_button;
  gtk_widget_show (button_font_sel_cancel);
  GTK_WIDGET_SET_FLAGS (button_font_sel_cancel, GTK_CAN_DEFAULT);

  button_font_sel_apply = GTK_FONT_SELECTION_DIALOG (font_sel_window)->apply_button;
  gtk_widget_show (button_font_sel_apply);
  GTK_WIDGET_SET_FLAGS (button_font_sel_apply, GTK_CAN_DEFAULT);

  font_sel = GTK_FONT_SELECTION_DIALOG (font_sel_window)->fontsel;
  gtk_widget_show (font_sel);
  gtk_container_set_border_width (GTK_CONTAINER (font_sel), 4);

  g_signal_connect ((gpointer) font_sel_window, "delete_event",
                    G_CALLBACK (on_button_font_sel_cancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_font_sel_ok, "clicked",
                    G_CALLBACK (on_button_font_sel_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_font_sel_cancel, "clicked",
                    G_CALLBACK (on_button_font_sel_cancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_font_sel_apply, "clicked",
                    G_CALLBACK (on_button_font_sel_apply_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (font_sel_window, font_sel_window, "font_sel_window");
  GLADE_HOOKUP_OBJECT_NO_REF (font_sel_window, button_font_sel_ok, "button_font_sel_ok");
  GLADE_HOOKUP_OBJECT_NO_REF (font_sel_window, button_font_sel_cancel, "button_font_sel_cancel");
  GLADE_HOOKUP_OBJECT_NO_REF (font_sel_window, button_font_sel_apply, "button_font_sel_apply");
  GLADE_HOOKUP_OBJECT_NO_REF (font_sel_window, font_sel, "font_sel");

  return font_sel_window;
}

GtkWidget*
create_window_live (void)
{
  GtkWidget *window_live;
  GtkWidget *vbox36;
  GtkWidget *progressbar_live;
  GtkWidget *hbox50;
  GtkWidget *vbox38;
  GtkWidget *scrolledwindow8;
  GtkWidget *treeview_result;
  GtkWidget *hscale_area;
  GtkWidget *scrolledwindow9;
  GtkWidget *treeview_commentary;
  GtkWidget *hbox48;
  GtkWidget *button_pause;
  GtkWidget *alignment16;
  GtkWidget *hbox51;
  GtkWidget *image56;
  GtkWidget *label72;
  GtkWidget *button_resume;
  GtkWidget *alignment17;
  GtkWidget *hbox52;
  GtkWidget *image57;
  GtkWidget *label73;
  GtkWidget *button_live_close;
  GtkObject *spinbutton_speed_adj;
  GtkWidget *spinbutton_speed;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  window_live = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (window_live), 6);
  gtk_window_set_title (GTK_WINDOW (window_live), _("Live game"));
  gtk_window_set_position (GTK_WINDOW (window_live), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window_live), 450, 550);

  vbox36 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox36);
  gtk_container_add (GTK_CONTAINER (window_live), vbox36);

  progressbar_live = gtk_progress_bar_new ();
  gtk_widget_show (progressbar_live);
  gtk_box_pack_start (GTK_BOX (vbox36), progressbar_live, FALSE, FALSE, 0);

  hbox50 = gtk_hbox_new (FALSE, 3);
  gtk_widget_show (hbox50);
  gtk_box_pack_start (GTK_BOX (vbox36), hbox50, TRUE, TRUE, 0);

  vbox38 = gtk_vbox_new (FALSE, 3);
  gtk_widget_show (vbox38);
  gtk_box_pack_start (GTK_BOX (hbox50), vbox38, TRUE, TRUE, 0);

  scrolledwindow8 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow8);
  gtk_box_pack_start (GTK_BOX (vbox38), scrolledwindow8, FALSE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow8), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow8), GTK_SHADOW_ETCHED_IN);

  treeview_result = gtk_tree_view_new ();
  gtk_widget_show (treeview_result);
  gtk_container_add (GTK_CONTAINER (scrolledwindow8), treeview_result);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (treeview_result), FALSE);

  hscale_area = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (5, 0, 10, 0, 0, 0)));
  gtk_widget_show (hscale_area);
  gtk_box_pack_start (GTK_BOX (vbox38), hscale_area, FALSE, TRUE, 0);
  gtk_scale_set_draw_value (GTK_SCALE (hscale_area), FALSE);

  scrolledwindow9 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow9);
  gtk_box_pack_start (GTK_BOX (vbox38), scrolledwindow9, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow9), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow9), GTK_SHADOW_ETCHED_IN);

  treeview_commentary = gtk_tree_view_new ();
  gtk_widget_show (treeview_commentary);
  gtk_container_add (GTK_CONTAINER (scrolledwindow9), treeview_commentary);

  hbox48 = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (hbox48);
  gtk_box_pack_start (GTK_BOX (vbox36), hbox48, FALSE, TRUE, 5);

  button_pause = gtk_button_new ();
  gtk_widget_show (button_pause);
  gtk_box_pack_start (GTK_BOX (hbox48), button_pause, FALSE, FALSE, 0);
  gtk_widget_add_accelerator (button_pause, "clicked", accel_group,
                              GDK_space, 0,
                              GTK_ACCEL_VISIBLE);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button_pause), alignment16);

  hbox51 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox51);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox51);

  image56 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image56);
  gtk_box_pack_start (GTK_BOX (hbox51), image56, FALSE, FALSE, 0);

  label72 = gtk_label_new_with_mnemonic (_("Pause"));
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox51), label72, FALSE, FALSE, 0);

  button_resume = gtk_button_new ();
  gtk_box_pack_start (GTK_BOX (hbox48), button_resume, FALSE, FALSE, 0);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button_resume), alignment17);

  hbox52 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox52);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox52);

  image57 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image57);
  gtk_box_pack_start (GTK_BOX (hbox52), image57, FALSE, FALSE, 0);

  label73 = gtk_label_new_with_mnemonic (_("Resume"));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox52), label73, FALSE, FALSE, 0);

  button_live_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (button_live_close);
  gtk_box_pack_start (GTK_BOX (hbox48), button_live_close, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (button_live_close, FALSE);

  spinbutton_speed_adj = gtk_adjustment_new (0, -10, 20, 1, 10, 10);
  spinbutton_speed = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_speed_adj), 1, 0);
  gtk_widget_show (spinbutton_speed);
  gtk_box_pack_end (GTK_BOX (hbox48), spinbutton_speed, FALSE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_speed), TRUE);

  g_signal_connect ((gpointer) window_live, "delete_event",
                    G_CALLBACK (on_live_window_delete_event),
                    NULL);
  g_signal_connect ((gpointer) button_pause, "clicked",
                    G_CALLBACK (on_button_pause_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_resume, "clicked",
                    G_CALLBACK (on_button_resume_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_live_close, "clicked",
                    G_CALLBACK (on_button_live_close_clicked),
                    NULL);
  g_signal_connect ((gpointer) spinbutton_speed, "value_changed",
                    G_CALLBACK (on_spinbutton_speed_value_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_live, window_live, "window_live");
  GLADE_HOOKUP_OBJECT (window_live, vbox36, "vbox36");
  GLADE_HOOKUP_OBJECT (window_live, progressbar_live, "progressbar_live");
  GLADE_HOOKUP_OBJECT (window_live, hbox50, "hbox50");
  GLADE_HOOKUP_OBJECT (window_live, vbox38, "vbox38");
  GLADE_HOOKUP_OBJECT (window_live, scrolledwindow8, "scrolledwindow8");
  GLADE_HOOKUP_OBJECT (window_live, treeview_result, "treeview_result");
  GLADE_HOOKUP_OBJECT (window_live, hscale_area, "hscale_area");
  GLADE_HOOKUP_OBJECT (window_live, scrolledwindow9, "scrolledwindow9");
  GLADE_HOOKUP_OBJECT (window_live, treeview_commentary, "treeview_commentary");
  GLADE_HOOKUP_OBJECT (window_live, hbox48, "hbox48");
  GLADE_HOOKUP_OBJECT (window_live, button_pause, "button_pause");
  GLADE_HOOKUP_OBJECT (window_live, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window_live, hbox51, "hbox51");
  GLADE_HOOKUP_OBJECT (window_live, image56, "image56");
  GLADE_HOOKUP_OBJECT (window_live, label72, "label72");
  GLADE_HOOKUP_OBJECT (window_live, button_resume, "button_resume");
  GLADE_HOOKUP_OBJECT (window_live, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window_live, hbox52, "hbox52");
  GLADE_HOOKUP_OBJECT (window_live, image57, "image57");
  GLADE_HOOKUP_OBJECT (window_live, label73, "label73");
  GLADE_HOOKUP_OBJECT (window_live, button_live_close, "button_live_close");
  GLADE_HOOKUP_OBJECT (window_live, spinbutton_speed, "spinbutton_speed");

  gtk_window_add_accel_group (GTK_WINDOW (window_live), accel_group);

  return window_live;
}

GtkWidget*
create_help_window (void)
{
  GtkWidget *help_window;
  GtkWidget *vbox27;
  GtkWidget *scrolledwindow5;
  GtkWidget *text_view_help;
  GtkWidget *button_help_close;
  GtkWidget *alignment11;
  GtkWidget *hbox40;
  GtkWidget *image40;
  GtkWidget *label59;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  help_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (help_window), 6);
  gtk_window_set_title (GTK_WINDOW (help_window), _("Bygfoot help"));
  gtk_window_set_position (GTK_WINDOW (help_window), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (help_window), 550, 650);

  vbox27 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox27);
  gtk_container_add (GTK_CONTAINER (help_window), vbox27);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_box_pack_start (GTK_BOX (vbox27), scrolledwindow5, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_SHADOW_IN);

  text_view_help = gtk_text_view_new ();
  gtk_widget_show (text_view_help);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), text_view_help);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (text_view_help), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (text_view_help), GTK_WRAP_WORD);
  gtk_text_view_set_indent (GTK_TEXT_VIEW (text_view_help), 5);

  button_help_close = gtk_button_new ();
  gtk_widget_show (button_help_close);
  gtk_box_pack_start (GTK_BOX (vbox27), button_help_close, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_help_close), 2);
  gtk_tooltips_set_tip (tooltips, button_help_close, _("Esc / Return / Space"), NULL);
  gtk_widget_add_accelerator (button_help_close, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (button_help_close, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (button_help_close, "clicked", accel_group,
                              GDK_space, 0,
                              GTK_ACCEL_VISIBLE);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_help_close), alignment11);

  hbox40 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox40);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox40);

  image40 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image40);
  gtk_box_pack_start (GTK_BOX (hbox40), image40, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("Close"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox40), label59, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_help_close, "clicked",
                    G_CALLBACK (on_button_help_close_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (help_window, help_window, "help_window");
  GLADE_HOOKUP_OBJECT (help_window, vbox27, "vbox27");
  GLADE_HOOKUP_OBJECT (help_window, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (help_window, text_view_help, "text_view_help");
  GLADE_HOOKUP_OBJECT (help_window, button_help_close, "button_help_close");
  GLADE_HOOKUP_OBJECT (help_window, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (help_window, hbox40, "hbox40");
  GLADE_HOOKUP_OBJECT (help_window, image40, "image40");
  GLADE_HOOKUP_OBJECT (help_window, label59, "label59");
  GLADE_HOOKUP_OBJECT_NO_REF (help_window, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (help_window), accel_group);

  return help_window;
}

