/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "options_callbacks.h"
#include "options_interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_options (void)
{
  GtkWidget *window_options;
  GtkWidget *vbox1;
  GtkWidget *notebook1;
  GtkWidget *hbox2;
  GtkWidget *vbox3;
  GtkWidget *checkbutton_conf_new_week_round;
  GtkWidget *checkbutton_conf_quit;
  GtkWidget *checkbutton_save_overwrite;
  GtkWidget *checkbutton_maximize;
  GtkWidget *checkbutton_pref_mess;
  GtkWidget *vseparator1;
  GtkWidget *table1;
  GtkWidget *checkbutton_autosave;
  GtkWidget *hbox3;
  GtkWidget *label6;
  GtkObject *spinbutton_autosave_adj;
  GtkWidget *spinbutton_autosave;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkObject *spinbutton_precision_adj;
  GtkWidget *spinbutton_precision;
  GtkObject *spinbutton_refresh_adj;
  GtkWidget *spinbutton_refresh;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *entry_names_file;
  GtkWidget *entry_constants_file;
  GtkWidget *entry_user_file;
  GtkWidget *label1;
  GtkWidget *empty_notebook_page;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *hseparator1;
  GtkWidget *hbox1;
  GtkWidget *vbox2;
  GtkWidget *checkbutton_save_global;
  GtkWidget *checkbutton_save_user;
  GtkWidget *button_ok;
  GtkWidget *button_cancel;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  window_options = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (window_options), 5);
  gtk_window_set_title (GTK_WINDOW (window_options), _("window1"));
  gtk_window_set_position (GTK_WINDOW (window_options), GTK_WIN_POS_CENTER);

  vbox1 = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window_options), vbox1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, TRUE, TRUE, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (notebook1), hbox2);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), hbox2,
                                      FALSE, FALSE, GTK_PACK_START);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox3, TRUE, TRUE, 0);

  checkbutton_conf_new_week_round = gtk_check_button_new_with_mnemonic (_("Confirm new week round"));
  gtk_widget_show (checkbutton_conf_new_week_round);
  gtk_box_pack_start (GTK_BOX (vbox3), checkbutton_conf_new_week_round, FALSE, FALSE, 0);

  checkbutton_conf_quit = gtk_check_button_new_with_mnemonic (_("Confirm quit"));
  gtk_widget_show (checkbutton_conf_quit);
  gtk_box_pack_start (GTK_BOX (vbox3), checkbutton_conf_quit, FALSE, FALSE, 0);

  checkbutton_save_overwrite = gtk_check_button_new_with_mnemonic (_("Save overwrites"));
  gtk_widget_show (checkbutton_save_overwrite);
  gtk_box_pack_start (GTK_BOX (vbox3), checkbutton_save_overwrite, FALSE, FALSE, 0);

  checkbutton_maximize = gtk_check_button_new_with_mnemonic (_("Maximize main window"));
  gtk_widget_show (checkbutton_maximize);
  gtk_box_pack_start (GTK_BOX (vbox3), checkbutton_maximize, FALSE, FALSE, 0);

  checkbutton_pref_mess = gtk_check_button_new_with_mnemonic (_("Prefer messages"));
  gtk_widget_show (checkbutton_pref_mess);
  gtk_box_pack_start (GTK_BOX (vbox3), checkbutton_pref_mess, FALSE, FALSE, 0);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_box_pack_start (GTK_BOX (hbox2), vseparator1, FALSE, FALSE, 0);
  gtk_widget_set_size_request (vseparator1, 10, 1);

  table1 = gtk_table_new (6, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (hbox2), table1, TRUE, TRUE, 0);

  checkbutton_autosave = gtk_check_button_new_with_mnemonic (_("Autosave"));
  gtk_widget_show (checkbutton_autosave);
  gtk_table_attach (GTK_TABLE (table1), checkbutton_autosave, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_table_attach (GTK_TABLE (table1), hbox3, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label6 = gtk_label_new (_("Autosave interval "));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_LEFT);

  spinbutton_autosave_adj = gtk_adjustment_new (1, 1, 20, 1, 10, 10);
  spinbutton_autosave = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_autosave_adj), 1, 0);
  gtk_widget_show (spinbutton_autosave);
  gtk_box_pack_start (GTK_BOX (hbox3), spinbutton_autosave, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_autosave), TRUE);

  label7 = gtk_label_new (_("Player attribute precision "));
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table1), label7, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label7), GTK_JUSTIFY_LEFT);

  label8 = gtk_label_new (_("Player list refresh rate "));
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table1), label8, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label8), GTK_JUSTIFY_LEFT);

  spinbutton_precision_adj = gtk_adjustment_new (1, 0, 3, 1, 10, 10);
  spinbutton_precision = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_precision_adj), 1, 0);
  gtk_widget_show (spinbutton_precision);
  gtk_table_attach (GTK_TABLE (table1), spinbutton_precision, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_precision), TRUE);

  spinbutton_refresh_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  spinbutton_refresh = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_refresh_adj), 1, 0);
  gtk_widget_show (spinbutton_refresh);
  gtk_table_attach (GTK_TABLE (table1), spinbutton_refresh, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_refresh), TRUE);

  label9 = gtk_label_new (_("Player names file "));
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table1), label9, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_LEFT);

  label10 = gtk_label_new (_("Constants file "));
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table1), label10, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_LEFT);

  label11 = gtk_label_new (_("Default user conf file "));
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table1), label11, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label11), GTK_JUSTIFY_LEFT);

  entry_names_file = gtk_entry_new ();
  gtk_widget_show (entry_names_file);
  gtk_table_attach (GTK_TABLE (table1), entry_names_file, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry_constants_file = gtk_entry_new ();
  gtk_widget_show (entry_constants_file);
  gtk_table_attach (GTK_TABLE (table1), entry_constants_file, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry_user_file = gtk_entry_new ();
  gtk_widget_show (entry_user_file);
  gtk_table_attach (GTK_TABLE (table1), entry_user_file, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label1 = gtk_label_new (_("Global"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_LEFT);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label2 = gtk_label_new (_("Live game"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_LEFT);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label3 = gtk_label_new (_("Misc."));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label4 = gtk_label_new (_("Player attributes"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label4);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label5 = gtk_label_new (_("label5"));
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label5);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, FALSE, FALSE, 0);
  gtk_widget_set_size_request (hseparator1, 1, 10);

  hbox1 = gtk_hbox_new (FALSE, 3);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, FALSE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox2, FALSE, FALSE, 0);

  checkbutton_save_global = gtk_check_button_new_with_mnemonic (_("Save global settings to file"));
  gtk_widget_show (checkbutton_save_global);
  gtk_box_pack_start (GTK_BOX (vbox2), checkbutton_save_global, FALSE, FALSE, 0);

  checkbutton_save_user = gtk_check_button_new_with_mnemonic (_("Save user settings to file"));
  gtk_widget_show (checkbutton_save_user);
  gtk_box_pack_start (GTK_BOX (vbox2), checkbutton_save_user, FALSE, FALSE, 0);

  button_ok = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (button_ok);
  gtk_box_pack_start (GTK_BOX (hbox1), button_ok, TRUE, TRUE, 0);

  button_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button_cancel);
  gtk_box_pack_start (GTK_BOX (hbox1), button_cancel, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, button_cancel, _("Esc"), NULL);
  gtk_widget_add_accelerator (button_cancel, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  g_signal_connect ((gpointer) button_ok, "clicked",
                    G_CALLBACK (on_button_options_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_cancel, "clicked",
                    G_CALLBACK (on_button_options_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_options, window_options, "window_options");
  GLADE_HOOKUP_OBJECT (window_options, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window_options, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window_options, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window_options, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (window_options, checkbutton_conf_new_week_round, "checkbutton_conf_new_week_round");
  GLADE_HOOKUP_OBJECT (window_options, checkbutton_conf_quit, "checkbutton_conf_quit");
  GLADE_HOOKUP_OBJECT (window_options, checkbutton_save_overwrite, "checkbutton_save_overwrite");
  GLADE_HOOKUP_OBJECT (window_options, checkbutton_maximize, "checkbutton_maximize");
  GLADE_HOOKUP_OBJECT (window_options, checkbutton_pref_mess, "checkbutton_pref_mess");
  GLADE_HOOKUP_OBJECT (window_options, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (window_options, table1, "table1");
  GLADE_HOOKUP_OBJECT (window_options, checkbutton_autosave, "checkbutton_autosave");
  GLADE_HOOKUP_OBJECT (window_options, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window_options, label6, "label6");
  GLADE_HOOKUP_OBJECT (window_options, spinbutton_autosave, "spinbutton_autosave");
  GLADE_HOOKUP_OBJECT (window_options, label7, "label7");
  GLADE_HOOKUP_OBJECT (window_options, label8, "label8");
  GLADE_HOOKUP_OBJECT (window_options, spinbutton_precision, "spinbutton_precision");
  GLADE_HOOKUP_OBJECT (window_options, spinbutton_refresh, "spinbutton_refresh");
  GLADE_HOOKUP_OBJECT (window_options, label9, "label9");
  GLADE_HOOKUP_OBJECT (window_options, label10, "label10");
  GLADE_HOOKUP_OBJECT (window_options, label11, "label11");
  GLADE_HOOKUP_OBJECT (window_options, entry_names_file, "entry_names_file");
  GLADE_HOOKUP_OBJECT (window_options, entry_constants_file, "entry_constants_file");
  GLADE_HOOKUP_OBJECT (window_options, entry_user_file, "entry_user_file");
  GLADE_HOOKUP_OBJECT (window_options, label1, "label1");
  GLADE_HOOKUP_OBJECT (window_options, label2, "label2");
  GLADE_HOOKUP_OBJECT (window_options, label3, "label3");
  GLADE_HOOKUP_OBJECT (window_options, label4, "label4");
  GLADE_HOOKUP_OBJECT (window_options, label5, "label5");
  GLADE_HOOKUP_OBJECT (window_options, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (window_options, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window_options, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (window_options, checkbutton_save_global, "checkbutton_save_global");
  GLADE_HOOKUP_OBJECT (window_options, checkbutton_save_user, "checkbutton_save_user");
  GLADE_HOOKUP_OBJECT (window_options, button_ok, "button_ok");
  GLADE_HOOKUP_OBJECT (window_options, button_cancel, "button_cancel");
  GLADE_HOOKUP_OBJECT_NO_REF (window_options, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (window_options), accel_group);

  return window_options;
}

