/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "options_callbacks.h"
#include "options_interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_opt_window (void)
{
  GtkWidget *opt_window;
  GtkWidget *vbox39;
  GtkWidget *notebook1;
  GtkWidget *frame1;
  GtkWidget *hbox65;
  GtkWidget *vbox32;
  GtkWidget *label53;
  GtkWidget *hbox66;
  GtkWidget *radio_show1;
  GSList *radio_show1_group = NULL;
  GtkWidget *radio_show2;
  GtkWidget *check_show_live;
  GtkWidget *vbox34;
  GtkWidget *hbox21;
  GtkWidget *label43;
  GtkObject *spin_live_duration_adj;
  GtkWidget *spin_live_duration;
  GtkWidget *hbox39;
  GtkWidget *label58;
  GtkWidget *check_live_tendency;
  GtkWidget *hbox34;
  GtkWidget *button_opt_change_font;
  GtkWidget *alignment9;
  GtkWidget *hbox35;
  GtkWidget *image30;
  GtkWidget *label55;
  GtkWidget *label54;
  GtkWidget *hbox46;
  GtkWidget *label71;
  GtkWidget *entry_team_name;
  GtkWidget *vseparator3;
  GtkWidget *vbox33;
  GtkWidget *checkbutton_maximize;
  GtkWidget *hbox22;
  GtkWidget *label45;
  GtkWidget *radio_mess1;
  GSList *radio_mess1_group = NULL;
  GtkWidget *radio_mess2;
  GtkWidget *radio_mess3;
  GtkWidget *checkbutton_prefer_mess;
  GtkWidget *check_jobs;
  GtkWidget *eventbox3;
  GtkWidget *hbox67;
  GtkWidget *checkbutton_rearrange;
  GtkWidget *checkbutton_swap;
  GtkWidget *checkbutton_fit_colors;
  GtkWidget *label89;
  GtkWidget *label83;
  GtkWidget *frame2;
  GtkWidget *vbox35;
  GtkWidget *check_overwrite;
  GtkWidget *hbox62;
  GtkWidget *checkbutton_autosave;
  GtkObject *spinbutton_autosave_adj;
  GtkWidget *spinbutton_autosave;
  GtkWidget *label82;
  GtkWidget *label90;
  GtkWidget *label84;
  GtkWidget *frame3;
  GtkWidget *vbox36;
  GtkWidget *hbox63;
  GtkWidget *checkbutton_sort_transfers;
  GtkWidget *hbox64;
  GtkWidget *radiobutton_sort_pos;
  GSList *radiobutton_sort_pos_group = NULL;
  GtkWidget *radiobutton_sort_skill;
  GtkWidget *radiobutton_sort_age;
  GtkWidget *radiobutton_sort_etal;
  GtkWidget *radiobutton_sort_league;
  GtkWidget *vseparator1;
  GtkWidget *checkbutton_sort_asc;
  GtkWidget *hseparator11;
  GtkWidget *checkbutton_notify;
  GtkWidget *frame7;
  GtkWidget *hbox52;
  GtkWidget *vbox28;
  GtkWidget *checkbutton_notify_skill;
  GtkWidget *checkbutton_notify_etal;
  GtkWidget *checkbutton_notify_age;
  GtkWidget *checkbutton_notify_value;
  GtkWidget *checkbutton_notify_positions;
  GtkWidget *checkbutton_notify_league;
  GtkWidget *label78;
  GtkWidget *vbox29;
  GtkObject *spinbutton_notify_skill1_adj;
  GtkWidget *spinbutton_notify_skill1;
  GtkObject *spinbutton_notify_etal1_adj;
  GtkWidget *spinbutton_notify_etal1;
  GtkObject *spinbutton_notify_age1_adj;
  GtkWidget *spinbutton_notify_age1;
  GtkObject *spinbutton_notify_value_adj;
  GtkWidget *spinbutton_notify_value;
  GtkWidget *checkbutton_notify_pos0;
  GtkWidget *checkbutton_notify_league1;
  GtkWidget *checkbutton_notify_league4;
  GtkWidget *vbox30;
  GtkWidget *label73;
  GtkWidget *label74;
  GtkWidget *label75;
  GtkWidget *label76;
  GtkWidget *hbox54;
  GtkWidget *checkbutton_notify_pos1;
  GtkWidget *checkbutton_notify_pos2;
  GtkWidget *checkbutton_notify_league2;
  GtkWidget *checkbutton_notify_league5;
  GtkWidget *vboxa31;
  GtkObject *spinbutton_notify_skill2_adj;
  GtkWidget *spinbutton_notify_skill2;
  GtkObject *spinbutton_notify_etal2_adj;
  GtkWidget *spinbutton_notify_etal2;
  GtkObject *spinbutton_notify_age2_adj;
  GtkWidget *spinbutton_notify_age2;
  GtkWidget *label77;
  GtkWidget *hbox53;
  GtkWidget *checkbutton_notify_pos3;
  GtkWidget *checkbutton_notify_league3;
  GtkWidget *checkbutton_notify_league6;
  GtkWidget *label95;
  GtkWidget *label91;
  GtkWidget *label85;
  GtkWidget *frame4;
  GtkWidget *vbox37;
  GtkWidget *check_conf_new_week;
  GtkWidget *check_conf_unfit;
  GtkWidget *check_conf_quit;
  GtkWidget *label92;
  GtkWidget *label86;
  GtkWidget *frame5;
  GtkWidget *vbox41;
  GtkWidget *hbox68;
  GtkWidget *vbox42;
  GtkWidget *label98;
  GtkWidget *hseparator12;
  GtkWidget *label109;
  GtkWidget *label110;
  GtkWidget *label111;
  GtkWidget *label112;
  GtkWidget *label99;
  GtkWidget *label100;
  GtkWidget *label101;
  GtkWidget *label102;
  GtkWidget *label103;
  GtkWidget *label104;
  GtkWidget *label105;
  GtkWidget *label106;
  GtkWidget *label107;
  GtkWidget *label108;
  GtkWidget *label113;
  GtkWidget *label114;
  GtkWidget *vseparator6;
  GtkWidget *vbox45;
  GtkWidget *label130;
  GtkWidget *hseparator13;
  GtkWidget *check_att_name;
  GtkWidget *check_att_cpos;
  GtkWidget *check_att_pos;
  GtkWidget *check_att_cskill;
  GtkWidget *check_att_skill;
  GtkWidget *check_att_fit;
  GtkWidget *check_att_games;
  GtkWidget *check_att_goals;
  GtkWidget *check_att_status;
  GtkWidget *check_att_age;
  GtkWidget *check_att_etal;
  GtkWidget *check_att_booked;
  GtkWidget *check_att_value;
  GtkWidget *check_att_wage;
  GtkWidget *check_att_team;
  GtkWidget *check_att_league;
  GtkWidget *vseparator5;
  GtkWidget *vbox46;
  GtkWidget *label115;
  GtkWidget *hseparator14;
  GtkWidget *check_att2_name;
  GtkWidget *check_att2_cpos;
  GtkWidget *check_att2_pos;
  GtkWidget *check_att2_cskill;
  GtkWidget *check_att2_skill;
  GtkWidget *check_att2_fit;
  GtkWidget *check_att2_games;
  GtkWidget *check_att2_goals;
  GtkWidget *check_att2_status;
  GtkWidget *check_att2_age;
  GtkWidget *check_att2_etal;
  GtkWidget *check_att2_booked;
  GtkWidget *check_att2_value;
  GtkWidget *check_att2_wage;
  GtkWidget *check_att2_team;
  GtkWidget *check_att2_league;
  GtkWidget *label93;
  GtkWidget *label87;
  GtkWidget *frame8;
  GtkWidget *hbox69;
  GtkWidget *vbox50;
  GtkWidget *label136;
  GtkWidget *hseparator17;
  GtkWidget *vbox51;
  GtkWidget *eventbox4;
  GtkWidget *label140;
  GtkWidget *eventbox5;
  GtkWidget *label141;
  GtkWidget *eventbox6;
  GtkWidget *label142;
  GtkWidget *vseparator8;
  GtkWidget *vbox48;
  GtkWidget *label134;
  GtkWidget *hseparator15;
  GtkObject *spinbutton_interval_team_adj;
  GtkWidget *spinbutton_interval_team;
  GtkObject *spinbutton_max_team_adj;
  GtkWidget *spinbutton_max_team;
  GtkWidget *checkbutton_delete_team;
  GtkWidget *vseparator7;
  GtkWidget *vbox49;
  GtkWidget *label135;
  GtkWidget *hseparator16;
  GtkObject *spinbutton_interval_player_adj;
  GtkWidget *spinbutton_interval_player;
  GtkObject *spinbutton_max_player_adj;
  GtkWidget *spinbutton_max_player;
  GtkWidget *checkbutton_delete_player;
  GtkWidget *label132;
  GtkWidget *label131;
  GtkWidget *frame6;
  GtkWidget *vbox40;
  GtkWidget *checkbutton_skip_weeks;
  GtkWidget *label94;
  GtkWidget *label88;
  GtkWidget *hseparator8;
  GtkWidget *hbox25;
  GtkWidget *checkbutton_save_conf;
  GtkWidget *button_opt_ok;
  GtkWidget *alignment4;
  GtkWidget *hbox26;
  GtkWidget *image25;
  GtkWidget *label47;
  GtkWidget *button_opt_cancel;
  GtkWidget *alignment5;
  GtkWidget *hbox27;
  GtkWidget *image26;
  GtkWidget *label48;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  opt_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (opt_window), 5);
  gtk_window_set_title (GTK_WINDOW (opt_window), _("window1"));
  gtk_window_set_position (GTK_WINDOW (opt_window), GTK_WIN_POS_CENTER);

  vbox39 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox39);
  gtk_container_add (GTK_CONTAINER (opt_window), vbox39);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox39), notebook1, TRUE, TRUE, 0);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_container_add (GTK_CONTAINER (notebook1), frame1);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 5);

  hbox65 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox65);
  gtk_container_add (GTK_CONTAINER (frame1), hbox65);

  vbox32 = gtk_vbox_new (FALSE, 3);
  gtk_widget_show (vbox32);
  gtk_box_pack_start (GTK_BOX (hbox65), vbox32, FALSE, TRUE, 0);

  label53 = gtk_label_new (_("At the beginning of a new week show first"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (vbox32), label53, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label53), 0, 0.5);

  hbox66 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox66);
  gtk_box_pack_start (GTK_BOX (vbox32), hbox66, FALSE, FALSE, 0);

  radio_show1 = gtk_radio_button_new_with_mnemonic (NULL, _("League results"));
  gtk_widget_show (radio_show1);
  gtk_box_pack_start (GTK_BOX (hbox66), radio_show1, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, radio_show1, _("Show the results of all games in the league / cups my team participates in"), NULL);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_show1), radio_show1_group);
  radio_show1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_show1));

  radio_show2 = gtk_radio_button_new_with_mnemonic (NULL, _("My games plus preview"));
  gtk_widget_show (radio_show2);
  gtk_box_pack_start (GTK_BOX (hbox66), radio_show2, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, radio_show2, _("Show extended info on my games (with injuries etc.) and a preview of my next games"), NULL);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_show2), radio_show1_group);
  radio_show1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_show2));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radio_show2), TRUE);

  check_show_live = gtk_check_button_new_with_mnemonic (_("Show 'live' games"));
  gtk_widget_show (check_show_live);
  gtk_box_pack_start (GTK_BOX (vbox32), check_show_live, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, check_show_live, _("Show 'live' games"), NULL);

  vbox34 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox34);
  gtk_box_pack_start (GTK_BOX (vbox32), vbox34, FALSE, TRUE, 0);

  hbox21 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox21);
  gtk_box_pack_start (GTK_BOX (vbox34), hbox21, FALSE, TRUE, 0);

  label43 = gtk_label_new (_("       Live game duration factor   "));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox21), label43, FALSE, FALSE, 0);

  spin_live_duration_adj = gtk_adjustment_new (0, -100, 100, 1, 10, 10);
  spin_live_duration = gtk_spin_button_new (GTK_ADJUSTMENT (spin_live_duration_adj), 1, 0);
  gtk_widget_show (spin_live_duration);
  gtk_box_pack_start (GTK_BOX (hbox21), spin_live_duration, FALSE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, spin_live_duration, _("This can be between -100 and 100"), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spin_live_duration), TRUE);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (spin_live_duration), TRUE);

  hbox39 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox39);
  gtk_box_pack_start (GTK_BOX (vbox34), hbox39, FALSE, TRUE, 0);

  label58 = gtk_label_new (_("       "));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox39), label58, FALSE, FALSE, 0);

  check_live_tendency = gtk_check_button_new_with_mnemonic (_("Show live game tendency bar"));
  gtk_widget_show (check_live_tendency);
  gtk_box_pack_start (GTK_BOX (hbox39), check_live_tendency, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, check_live_tendency, _("The tendency bar shows in the live game window which team is closer to scoring a goal"), NULL);

  hbox34 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox34);
  gtk_box_pack_start (GTK_BOX (vbox32), hbox34, FALSE, TRUE, 0);

  button_opt_change_font = gtk_button_new ();
  gtk_widget_show (button_opt_change_font);
  gtk_box_pack_start (GTK_BOX (hbox34), button_opt_change_font, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_opt_change_font), 2);
  gtk_tooltips_set_tip (tooltips, button_opt_change_font, _("This affects the two windows in the main screen, the help window and the live game window"), NULL);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_opt_change_font), alignment9);

  hbox35 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox35);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox35);

  image30 = gtk_image_new_from_stock ("gtk-select-font", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox35), image30, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("Change font"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox35), label55, FALSE, FALSE, 0);

  label54 = gtk_label_new (_(" used in the main windows"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox34), label54, FALSE, FALSE, 0);

  hbox46 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox46);
  gtk_box_pack_start (GTK_BOX (vbox32), hbox46, FALSE, TRUE, 0);

  label71 = gtk_label_new (_("Change team name "));
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox46), label71, FALSE, FALSE, 0);

  entry_team_name = gtk_entry_new ();
  gtk_widget_show (entry_team_name);
  gtk_box_pack_start (GTK_BOX (hbox46), entry_team_name, FALSE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, entry_team_name, _("Change the name of your current team for this game. Use the Bygfoot Team Editor to change a team name permanently."), NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry_team_name), 49);

  vseparator3 = gtk_vseparator_new ();
  gtk_widget_show (vseparator3);
  gtk_box_pack_start (GTK_BOX (hbox65), vseparator3, FALSE, TRUE, 0);
  gtk_widget_set_size_request (vseparator3, 10, 1);

  vbox33 = gtk_vbox_new (FALSE, 3);
  gtk_widget_show (vbox33);
  gtk_box_pack_start (GTK_BOX (hbox65), vbox33, FALSE, FALSE, 0);

  checkbutton_maximize = gtk_check_button_new_with_mnemonic (_("Start maximized"));
  gtk_widget_show (checkbutton_maximize);
  gtk_box_pack_start (GTK_BOX (vbox33), checkbutton_maximize, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, checkbutton_maximize, _("Whether or not the main window appears maximized at startup. (NOTE: Some windowmanagers don't support this.) Of course, you have to save your settings to the conf file if you want a change of this variable to take effect."), NULL);

  hbox22 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox22);
  gtk_box_pack_start (GTK_BOX (vbox33), hbox22, FALSE, FALSE, 0);

  label45 = gtk_label_new (_("Messages"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox22), label45, FALSE, FALSE, 0);

  radio_mess1 = gtk_radio_button_new_with_mnemonic (NULL, _("Moving"));
  gtk_widget_show (radio_mess1);
  gtk_box_pack_start (GTK_BOX (hbox22), radio_mess1, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, radio_mess1, _("Messages slide into the message window from the right"), NULL);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_mess1), radio_mess1_group);
  radio_mess1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_mess1));

  radio_mess2 = gtk_radio_button_new_with_mnemonic (NULL, _("Static"));
  gtk_widget_show (radio_mess2);
  gtk_box_pack_start (GTK_BOX (hbox22), radio_mess2, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, radio_mess2, _("Messages just appear in the message window"), NULL);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_mess2), radio_mess1_group);
  radio_mess1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_mess2));

  radio_mess3 = gtk_radio_button_new_with_mnemonic (NULL, _("Off"));
  gtk_widget_show (radio_mess3);
  gtk_box_pack_start (GTK_BOX (hbox22), radio_mess3, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, radio_mess3, _("No messages"), NULL);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_mess3), radio_mess1_group);
  radio_mess1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_mess3));

  checkbutton_prefer_mess = gtk_check_button_new_with_mnemonic (_("Prefer messages to popups"));
  gtk_widget_show (checkbutton_prefer_mess);
  gtk_box_pack_start (GTK_BOX (vbox33), checkbutton_prefer_mess, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, checkbutton_prefer_mess, _("If checked, messages are shown instead of popups when possible (ie. when you don't have to make an 'OK/Cancel'-type of decision."), NULL);

  check_jobs = gtk_check_button_new_with_mnemonic (_("Show job offers"));
  gtk_widget_show (check_jobs);
  gtk_box_pack_start (GTK_BOX (vbox33), check_jobs, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, check_jobs, _("Whether or not other teams offer you a job when you are successful"), NULL);

  eventbox3 = gtk_event_box_new ();
  gtk_widget_show (eventbox3);
  gtk_box_pack_start (GTK_BOX (vbox33), eventbox3, FALSE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, eventbox3, _("Whether or not pressing the rearrange button or swapping two players adapts the team structure automatically"), NULL);

  hbox67 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox67);
  gtk_container_add (GTK_CONTAINER (eventbox3), hbox67);

  checkbutton_rearrange = gtk_check_button_new_with_mnemonic (_("Rearrange / "));
  gtk_widget_show (checkbutton_rearrange);
  gtk_box_pack_start (GTK_BOX (hbox67), checkbutton_rearrange, FALSE, FALSE, 0);

  checkbutton_swap = gtk_check_button_new_with_mnemonic (_("Swap  adapts team structure"));
  gtk_widget_show (checkbutton_swap);
  gtk_box_pack_start (GTK_BOX (hbox67), checkbutton_swap, FALSE, FALSE, 0);

  checkbutton_fit_colors = gtk_check_button_new_with_mnemonic (_("Show fitness colors"));
  gtk_widget_show (checkbutton_fit_colors);
  gtk_box_pack_start (GTK_BOX (vbox33), checkbutton_fit_colors, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, checkbutton_fit_colors, _("Whether fitness percentage is shown in green and red shades"), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_fit_colors), TRUE);

  label89 = gtk_label_new (_("Apperance and behaviour of the game"));
  gtk_widget_show (label89);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label89);

  label83 = gtk_label_new (_("Look & Feel"));
  gtk_widget_show (label83);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label83);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_container_add (GTK_CONTAINER (notebook1), frame2);
  gtk_container_set_border_width (GTK_CONTAINER (frame2), 5);

  vbox35 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox35);
  gtk_container_add (GTK_CONTAINER (frame2), vbox35);

  check_overwrite = gtk_check_button_new_with_mnemonic (_("Save overwrites old savegame"));
  gtk_widget_show (check_overwrite);
  gtk_box_pack_start (GTK_BOX (vbox35), check_overwrite, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, check_overwrite, _("If you uncheck this, clicking on 'Save' will pop up a 'Save as' window"), NULL);

  hbox62 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox62);
  gtk_box_pack_start (GTK_BOX (vbox35), hbox62, FALSE, TRUE, 0);

  checkbutton_autosave = gtk_check_button_new_with_mnemonic (_("Autosave every "));
  gtk_widget_show (checkbutton_autosave);
  gtk_box_pack_start (GTK_BOX (hbox62), checkbutton_autosave, FALSE, FALSE, 0);

  spinbutton_autosave_adj = gtk_adjustment_new (3, 1, 12, 1, 10, 10);
  spinbutton_autosave = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_autosave_adj), 1, 0);
  gtk_widget_show (spinbutton_autosave);
  gtk_box_pack_start (GTK_BOX (hbox62), spinbutton_autosave, FALSE, TRUE, 0);
  gtk_widget_set_sensitive (spinbutton_autosave, FALSE);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_autosave), TRUE);

  label82 = gtk_label_new (_("  weeks"));
  gtk_widget_show (label82);
  gtk_box_pack_start (GTK_BOX (hbox62), label82, FALSE, FALSE, 0);

  label90 = gtk_label_new (_("Options for loading and saving games"));
  gtk_widget_show (label90);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label90);

  label84 = gtk_label_new (_("Load & Save"));
  gtk_widget_show (label84);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label84);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_container_add (GTK_CONTAINER (notebook1), frame3);
  gtk_container_set_border_width (GTK_CONTAINER (frame3), 5);

  vbox36 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox36);
  gtk_container_add (GTK_CONTAINER (frame3), vbox36);

  hbox63 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox63);
  gtk_box_pack_start (GTK_BOX (vbox36), hbox63, FALSE, TRUE, 0);

  checkbutton_sort_transfers = gtk_check_button_new_with_mnemonic (_("Sort transfer list by"));
  gtk_widget_show (checkbutton_sort_transfers);
  gtk_box_pack_start (GTK_BOX (hbox63), checkbutton_sort_transfers, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton_sort_transfers), 2);

  hbox64 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox64);
  gtk_box_pack_start (GTK_BOX (hbox63), hbox64, FALSE, TRUE, 0);

  radiobutton_sort_pos = gtk_radio_button_new_with_mnemonic (NULL, _("Position"));
  gtk_widget_show (radiobutton_sort_pos);
  gtk_box_pack_start (GTK_BOX (hbox64), radiobutton_sort_pos, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_sort_pos), radiobutton_sort_pos_group);
  radiobutton_sort_pos_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_sort_pos));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton_sort_pos), TRUE);

  radiobutton_sort_skill = gtk_radio_button_new_with_mnemonic (NULL, _("Skill"));
  gtk_widget_show (radiobutton_sort_skill);
  gtk_box_pack_start (GTK_BOX (hbox64), radiobutton_sort_skill, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_sort_skill), radiobutton_sort_pos_group);
  radiobutton_sort_pos_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_sort_skill));

  radiobutton_sort_age = gtk_radio_button_new_with_mnemonic (NULL, _("Age"));
  gtk_widget_show (radiobutton_sort_age);
  gtk_box_pack_start (GTK_BOX (hbox64), radiobutton_sort_age, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_sort_age), radiobutton_sort_pos_group);
  radiobutton_sort_pos_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_sort_age));

  radiobutton_sort_etal = gtk_radio_button_new_with_mnemonic (NULL, _("Estimated talent"));
  gtk_widget_show (radiobutton_sort_etal);
  gtk_box_pack_start (GTK_BOX (hbox64), radiobutton_sort_etal, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_sort_etal), radiobutton_sort_pos_group);
  radiobutton_sort_pos_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_sort_etal));

  radiobutton_sort_league = gtk_radio_button_new_with_mnemonic (NULL, _("League"));
  gtk_widget_show (radiobutton_sort_league);
  gtk_box_pack_start (GTK_BOX (hbox64), radiobutton_sort_league, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_sort_league), radiobutton_sort_pos_group);
  radiobutton_sort_pos_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_sort_league));

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_box_pack_start (GTK_BOX (hbox64), vseparator1, FALSE, TRUE, 0);
  gtk_widget_set_size_request (vseparator1, 5, 1);

  checkbutton_sort_asc = gtk_check_button_new_with_mnemonic (_("Ascending"));
  gtk_widget_show (checkbutton_sort_asc);
  gtk_box_pack_start (GTK_BOX (hbox64), checkbutton_sort_asc, FALSE, FALSE, 0);

  hseparator11 = gtk_hseparator_new ();
  gtk_widget_show (hseparator11);
  gtk_box_pack_start (GTK_BOX (vbox36), hseparator11, FALSE, TRUE, 0);
  gtk_widget_set_size_request (hseparator11, 1, 10);

  checkbutton_notify = gtk_check_button_new_with_mnemonic (_("Notify me whenever a player appears on the transfer list who fulfills my conditions:"));
  gtk_widget_show (checkbutton_notify);
  gtk_box_pack_start (GTK_BOX (vbox36), checkbutton_notify, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, checkbutton_notify, _("Check this if you want Bygfoot to keep an eye on the transfer list for you."), NULL);

  frame7 = gtk_frame_new (NULL);
  gtk_widget_show (frame7);
  gtk_box_pack_start (GTK_BOX (vbox36), frame7, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame7), 5);

  hbox52 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox52);
  gtk_container_add (GTK_CONTAINER (frame7), hbox52);
  gtk_widget_set_sensitive (hbox52, FALSE);

  vbox28 = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (vbox28);
  gtk_box_pack_start (GTK_BOX (hbox52), vbox28, TRUE, TRUE, 0);

  checkbutton_notify_skill = gtk_check_button_new_with_mnemonic (_("Skill between "));
  gtk_widget_show (checkbutton_notify_skill);
  gtk_box_pack_start (GTK_BOX (vbox28), checkbutton_notify_skill, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton_notify_skill), 2);
  gtk_tooltips_set_tip (tooltips, checkbutton_notify_skill, _("Filter players by their skill"), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_notify_skill), TRUE);

  checkbutton_notify_etal = gtk_check_button_new_with_mnemonic (_("Estimated talent between "));
  gtk_widget_show (checkbutton_notify_etal);
  gtk_box_pack_start (GTK_BOX (vbox28), checkbutton_notify_etal, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton_notify_etal), 2);
  gtk_tooltips_set_tip (tooltips, checkbutton_notify_etal, _("Filter players by their estimated talent"), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_notify_etal), TRUE);

  checkbutton_notify_age = gtk_check_button_new_with_mnemonic (_("Age between "));
  gtk_widget_show (checkbutton_notify_age);
  gtk_box_pack_start (GTK_BOX (vbox28), checkbutton_notify_age, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton_notify_age), 2);
  gtk_tooltips_set_tip (tooltips, checkbutton_notify_age, _("Filter players by their age (NOTE: You must have at least a 'good' scout in order to be able to filter by age)"), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_notify_age), TRUE);

  checkbutton_notify_value = gtk_check_button_new_with_mnemonic (_("Estimated value less than"));
  gtk_widget_show (checkbutton_notify_value);
  gtk_box_pack_start (GTK_BOX (vbox28), checkbutton_notify_value, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton_notify_value), 2);
  gtk_tooltips_set_tip (tooltips, checkbutton_notify_value, _("Filter players by their estimated value"), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_notify_value), TRUE);

  checkbutton_notify_positions = gtk_check_button_new_with_mnemonic (_("Positions"));
  gtk_widget_show (checkbutton_notify_positions);
  gtk_box_pack_start (GTK_BOX (vbox28), checkbutton_notify_positions, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, checkbutton_notify_positions, _("Filter players by their position"), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_notify_positions), TRUE);

  checkbutton_notify_league = gtk_check_button_new_with_mnemonic (_("League"));
  gtk_widget_show (checkbutton_notify_league);
  gtk_box_pack_start (GTK_BOX (vbox28), checkbutton_notify_league, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, checkbutton_notify_league, _("Filter players by their league"), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_notify_league), TRUE);

  label78 = gtk_label_new ("");
  gtk_widget_show (label78);
  gtk_box_pack_start (GTK_BOX (vbox28), label78, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label78), 0, 4);

  vbox29 = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (vbox29);
  gtk_box_pack_start (GTK_BOX (hbox52), vbox29, TRUE, TRUE, 0);

  spinbutton_notify_skill1_adj = gtk_adjustment_new (1, 1, 9.9, 0.1, 10, 10);
  spinbutton_notify_skill1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_notify_skill1_adj), 0.1, 1);
  gtk_widget_show (spinbutton_notify_skill1);
  gtk_box_pack_start (GTK_BOX (vbox29), spinbutton_notify_skill1, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_notify_skill1), TRUE);

  spinbutton_notify_etal1_adj = gtk_adjustment_new (1, 1, 9.9, 0.1, 10, 10);
  spinbutton_notify_etal1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_notify_etal1_adj), 0.1, 1);
  gtk_widget_show (spinbutton_notify_etal1);
  gtk_box_pack_start (GTK_BOX (vbox29), spinbutton_notify_etal1, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_notify_etal1), TRUE);

  spinbutton_notify_age1_adj = gtk_adjustment_new (17, 17, 37, 1, 10, 10);
  spinbutton_notify_age1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_notify_age1_adj), 1, 0);
  gtk_widget_show (spinbutton_notify_age1);
  gtk_box_pack_start (GTK_BOX (vbox29), spinbutton_notify_age1, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_notify_age1), TRUE);

  spinbutton_notify_value_adj = gtk_adjustment_new (1.5e+06, 100000, 2e+06, 10000, 100000, 10);
  spinbutton_notify_value = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_notify_value_adj), 10000, 0);
  gtk_widget_show (spinbutton_notify_value);
  gtk_box_pack_start (GTK_BOX (vbox29), spinbutton_notify_value, FALSE, FALSE, 0);

  checkbutton_notify_pos0 = gtk_check_button_new_with_mnemonic (_("Goalie"));
  gtk_widget_show (checkbutton_notify_pos0);
  gtk_box_pack_start (GTK_BOX (vbox29), checkbutton_notify_pos0, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_notify_pos0), TRUE);

  checkbutton_notify_league1 = gtk_check_button_new_with_mnemonic (_("League 1"));
  gtk_widget_show (checkbutton_notify_league1);
  gtk_box_pack_start (GTK_BOX (vbox29), checkbutton_notify_league1, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_notify_league1), TRUE);

  checkbutton_notify_league4 = gtk_check_button_new_with_mnemonic (_("League 4"));
  gtk_widget_show (checkbutton_notify_league4);
  gtk_box_pack_start (GTK_BOX (vbox29), checkbutton_notify_league4, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_notify_league4), TRUE);

  vbox30 = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (vbox30);
  gtk_box_pack_start (GTK_BOX (hbox52), vbox30, TRUE, TRUE, 0);

  label73 = gtk_label_new (_("  and  "));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (vbox30), label73, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label73), 0, 4);

  label74 = gtk_label_new (_("  and  "));
  gtk_widget_show (label74);
  gtk_box_pack_start (GTK_BOX (vbox30), label74, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label74), 0, 4);

  label75 = gtk_label_new (_("  and  "));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (vbox30), label75, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label75), 0, 4);

  label76 = gtk_label_new ("");
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (vbox30), label76, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label76), 0, 4);

  hbox54 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox54);
  gtk_box_pack_start (GTK_BOX (vbox30), hbox54, FALSE, FALSE, 0);

  checkbutton_notify_pos1 = gtk_check_button_new_with_mnemonic (_("Defender   "));
  gtk_widget_show (checkbutton_notify_pos1);
  gtk_box_pack_start (GTK_BOX (hbox54), checkbutton_notify_pos1, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_notify_pos1), TRUE);

  checkbutton_notify_pos2 = gtk_check_button_new_with_mnemonic (_("Midfielder"));
  gtk_widget_show (checkbutton_notify_pos2);
  gtk_box_pack_start (GTK_BOX (hbox54), checkbutton_notify_pos2, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_notify_pos2), TRUE);

  checkbutton_notify_league2 = gtk_check_button_new_with_mnemonic (_("League 2"));
  gtk_widget_show (checkbutton_notify_league2);
  gtk_box_pack_start (GTK_BOX (vbox30), checkbutton_notify_league2, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_notify_league2), TRUE);

  checkbutton_notify_league5 = gtk_check_button_new_with_mnemonic (_("League 5"));
  gtk_widget_show (checkbutton_notify_league5);
  gtk_box_pack_start (GTK_BOX (vbox30), checkbutton_notify_league5, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_notify_league5), TRUE);

  vboxa31 = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (vboxa31);
  gtk_box_pack_start (GTK_BOX (hbox52), vboxa31, TRUE, TRUE, 0);

  spinbutton_notify_skill2_adj = gtk_adjustment_new (9.9, 1, 9.9, 0.1, 10, 10);
  spinbutton_notify_skill2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_notify_skill2_adj), 0.1, 1);
  gtk_widget_show (spinbutton_notify_skill2);
  gtk_box_pack_start (GTK_BOX (vboxa31), spinbutton_notify_skill2, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_notify_skill2), TRUE);

  spinbutton_notify_etal2_adj = gtk_adjustment_new (9.9, 1, 9.9, 0.1, 10, 10);
  spinbutton_notify_etal2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_notify_etal2_adj), 0.1, 1);
  gtk_widget_show (spinbutton_notify_etal2);
  gtk_box_pack_start (GTK_BOX (vboxa31), spinbutton_notify_etal2, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_notify_etal2), TRUE);

  spinbutton_notify_age2_adj = gtk_adjustment_new (37, 17, 37, 1, 10, 10);
  spinbutton_notify_age2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_notify_age2_adj), 1, 0);
  gtk_widget_show (spinbutton_notify_age2);
  gtk_box_pack_start (GTK_BOX (vboxa31), spinbutton_notify_age2, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_notify_age2), TRUE);

  label77 = gtk_label_new ("");
  gtk_widget_show (label77);
  gtk_box_pack_start (GTK_BOX (vboxa31), label77, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label77), 0, 4);

  hbox53 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox53);
  gtk_box_pack_start (GTK_BOX (vboxa31), hbox53, FALSE, TRUE, 0);

  checkbutton_notify_pos3 = gtk_check_button_new_with_mnemonic (_("Forward"));
  gtk_widget_show (checkbutton_notify_pos3);
  gtk_box_pack_start (GTK_BOX (hbox53), checkbutton_notify_pos3, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_notify_pos3), TRUE);

  checkbutton_notify_league3 = gtk_check_button_new_with_mnemonic (_("League 3"));
  gtk_widget_show (checkbutton_notify_league3);
  gtk_box_pack_start (GTK_BOX (vboxa31), checkbutton_notify_league3, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_notify_league3), TRUE);

  checkbutton_notify_league6 = gtk_check_button_new_with_mnemonic (_("International"));
  gtk_widget_show (checkbutton_notify_league6);
  gtk_box_pack_start (GTK_BOX (vboxa31), checkbutton_notify_league6, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_notify_league6), TRUE);

  label95 = gtk_label_new ("");
  gtk_widget_show (label95);
  gtk_frame_set_label_widget (GTK_FRAME (frame7), label95);

  label91 = gtk_label_new (_("Options concering the transfer list"));
  gtk_widget_show (label91);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label91);

  label85 = gtk_label_new (_("Transfers"));
  gtk_widget_show (label85);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label85);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_show (frame4);
  gtk_container_add (GTK_CONTAINER (notebook1), frame4);
  gtk_container_set_border_width (GTK_CONTAINER (frame4), 5);

  vbox37 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox37);
  gtk_container_add (GTK_CONTAINER (frame4), vbox37);

  check_conf_new_week = gtk_check_button_new_with_mnemonic (_("New week"));
  gtk_widget_show (check_conf_new_week);
  gtk_box_pack_start (GTK_BOX (vbox37), check_conf_new_week, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (check_conf_new_week), 2);
  gtk_tooltips_set_tip (tooltips, check_conf_new_week, _("Show a warning before beginning a new week"), NULL);

  check_conf_unfit = gtk_check_button_new_with_mnemonic (_("Unfit players in the team"));
  gtk_widget_show (check_conf_unfit);
  gtk_box_pack_start (GTK_BOX (vbox37), check_conf_unfit, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (check_conf_unfit), 2);
  gtk_tooltips_set_tip (tooltips, check_conf_unfit, _("Show a warning when injured or banned players are in the team when beginning a new week"), NULL);

  check_conf_quit = gtk_check_button_new_with_mnemonic (_("Quit when not saved"));
  gtk_widget_show (check_conf_quit);
  gtk_box_pack_start (GTK_BOX (vbox37), check_conf_quit, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (check_conf_quit), 2);
  gtk_tooltips_set_tip (tooltips, check_conf_quit, _("Show a warning if I want to quit with a game that isn't saved"), NULL);

  label92 = gtk_label_new (_("Whether to confirm certain actions"));
  gtk_widget_show (label92);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label92);

  label86 = gtk_label_new (_("Confirmations"));
  gtk_widget_show (label86);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label86);

  frame5 = gtk_frame_new (NULL);
  gtk_widget_show (frame5);
  gtk_container_add (GTK_CONTAINER (notebook1), frame5);
  gtk_container_set_border_width (GTK_CONTAINER (frame5), 5);

  vbox41 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox41);
  gtk_container_add (GTK_CONTAINER (frame5), vbox41);

  hbox68 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox68);
  gtk_box_pack_start (GTK_BOX (vbox41), hbox68, TRUE, TRUE, 0);

  vbox42 = gtk_vbox_new (TRUE, 5);
  gtk_widget_show (vbox42);
  gtk_box_pack_start (GTK_BOX (hbox68), vbox42, FALSE, TRUE, 0);

  label98 = gtk_label_new (_("Attribute"));
  gtk_widget_show (label98);
  gtk_box_pack_start (GTK_BOX (vbox42), label98, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label98), 1.11759e-08, 0.5);

  hseparator12 = gtk_hseparator_new ();
  gtk_widget_show (hseparator12);
  gtk_box_pack_start (GTK_BOX (vbox42), hseparator12, FALSE, TRUE, 0);
  gtk_widget_set_size_request (hseparator12, 1, 10);

  label109 = gtk_label_new (_("Name"));
  gtk_widget_show (label109);
  gtk_box_pack_start (GTK_BOX (vbox42), label109, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label109), 0, 0.5);

  label110 = gtk_label_new (_("Current position"));
  gtk_widget_show (label110);
  gtk_box_pack_start (GTK_BOX (vbox42), label110, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label110), 0, 0.5);

  label111 = gtk_label_new (_("Position"));
  gtk_widget_show (label111);
  gtk_box_pack_start (GTK_BOX (vbox42), label111, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label111), 0, 0.5);

  label112 = gtk_label_new (_("Current skill"));
  gtk_widget_show (label112);
  gtk_box_pack_start (GTK_BOX (vbox42), label112, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label112), 0, 0.5);

  label99 = gtk_label_new (_("Skill"));
  gtk_widget_show (label99);
  gtk_box_pack_start (GTK_BOX (vbox42), label99, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label99), 0, 0.5);

  label100 = gtk_label_new (_("Fitness"));
  gtk_widget_show (label100);
  gtk_box_pack_start (GTK_BOX (vbox42), label100, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label100), 0, 0.5);

  label101 = gtk_label_new (_("Games"));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (vbox42), label101, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label101), 0, 0.5);

  label102 = gtk_label_new (_("Goals"));
  gtk_widget_show (label102);
  gtk_box_pack_start (GTK_BOX (vbox42), label102, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label102), 0, 0.5);

  label103 = gtk_label_new (_("Status"));
  gtk_widget_show (label103);
  gtk_box_pack_start (GTK_BOX (vbox42), label103, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label103), 0, 0.5);

  label104 = gtk_label_new (_("Age"));
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (vbox42), label104, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label104), 0, 0.5);

  label105 = gtk_label_new (_("Estimated talent"));
  gtk_widget_show (label105);
  gtk_box_pack_start (GTK_BOX (vbox42), label105, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label105), 0, 0.5);

  label106 = gtk_label_new (_("Yellow cards"));
  gtk_widget_show (label106);
  gtk_box_pack_start (GTK_BOX (vbox42), label106, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label106), 0, 0.5);

  label107 = gtk_label_new (_("Value"));
  gtk_widget_show (label107);
  gtk_box_pack_start (GTK_BOX (vbox42), label107, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label107), 0, 0.5);

  label108 = gtk_label_new (_("Wage"));
  gtk_widget_show (label108);
  gtk_box_pack_start (GTK_BOX (vbox42), label108, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label108), 0, 0.5);

  label113 = gtk_label_new (_("Team"));
  gtk_widget_show (label113);
  gtk_box_pack_start (GTK_BOX (vbox42), label113, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label113), 0, 0.5);

  label114 = gtk_label_new (_("League"));
  gtk_widget_show (label114);
  gtk_box_pack_start (GTK_BOX (vbox42), label114, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label114), 0, 0.5);

  vseparator6 = gtk_vseparator_new ();
  gtk_widget_show (vseparator6);
  gtk_box_pack_start (GTK_BOX (hbox68), vseparator6, FALSE, TRUE, 0);
  gtk_widget_set_size_request (vseparator6, 10, 1);

  vbox45 = gtk_vbox_new (TRUE, 0);
  gtk_widget_show (vbox45);
  gtk_box_pack_start (GTK_BOX (hbox68), vbox45, FALSE, TRUE, 0);

  label130 = gtk_label_new (_("Player list 1"));
  gtk_widget_show (label130);
  gtk_box_pack_start (GTK_BOX (vbox45), label130, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label130), 2.23517e-10, 0.5);

  hseparator13 = gtk_hseparator_new ();
  gtk_widget_show (hseparator13);
  gtk_box_pack_start (GTK_BOX (vbox45), hseparator13, FALSE, TRUE, 0);
  gtk_widget_set_size_request (hseparator13, 1, 10);

  check_att_name = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att_name);
  gtk_box_pack_start (GTK_BOX (vbox45), check_att_name, FALSE, FALSE, 0);

  check_att_cpos = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att_cpos);
  gtk_box_pack_start (GTK_BOX (vbox45), check_att_cpos, FALSE, FALSE, 0);

  check_att_pos = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att_pos);
  gtk_box_pack_start (GTK_BOX (vbox45), check_att_pos, FALSE, FALSE, 0);

  check_att_cskill = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att_cskill);
  gtk_box_pack_start (GTK_BOX (vbox45), check_att_cskill, FALSE, FALSE, 0);

  check_att_skill = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att_skill);
  gtk_box_pack_start (GTK_BOX (vbox45), check_att_skill, FALSE, FALSE, 0);

  check_att_fit = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att_fit);
  gtk_box_pack_start (GTK_BOX (vbox45), check_att_fit, FALSE, FALSE, 0);

  check_att_games = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att_games);
  gtk_box_pack_start (GTK_BOX (vbox45), check_att_games, FALSE, FALSE, 0);

  check_att_goals = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att_goals);
  gtk_box_pack_start (GTK_BOX (vbox45), check_att_goals, FALSE, FALSE, 0);

  check_att_status = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att_status);
  gtk_box_pack_start (GTK_BOX (vbox45), check_att_status, FALSE, FALSE, 0);

  check_att_age = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att_age);
  gtk_box_pack_start (GTK_BOX (vbox45), check_att_age, FALSE, FALSE, 0);

  check_att_etal = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att_etal);
  gtk_box_pack_start (GTK_BOX (vbox45), check_att_etal, FALSE, FALSE, 0);

  check_att_booked = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att_booked);
  gtk_box_pack_start (GTK_BOX (vbox45), check_att_booked, FALSE, FALSE, 0);

  check_att_value = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att_value);
  gtk_box_pack_start (GTK_BOX (vbox45), check_att_value, FALSE, FALSE, 0);

  check_att_wage = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att_wage);
  gtk_box_pack_start (GTK_BOX (vbox45), check_att_wage, FALSE, FALSE, 0);

  check_att_team = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att_team);
  gtk_box_pack_start (GTK_BOX (vbox45), check_att_team, FALSE, FALSE, 0);

  check_att_league = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att_league);
  gtk_box_pack_start (GTK_BOX (vbox45), check_att_league, FALSE, FALSE, 0);

  vseparator5 = gtk_vseparator_new ();
  gtk_widget_show (vseparator5);
  gtk_box_pack_start (GTK_BOX (hbox68), vseparator5, FALSE, TRUE, 0);
  gtk_widget_set_size_request (vseparator5, 10, 1);

  vbox46 = gtk_vbox_new (TRUE, 0);
  gtk_widget_show (vbox46);
  gtk_box_pack_start (GTK_BOX (hbox68), vbox46, TRUE, TRUE, 0);

  label115 = gtk_label_new (_("Player list 2"));
  gtk_widget_show (label115);
  gtk_box_pack_start (GTK_BOX (vbox46), label115, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label115), 0, 0.5);

  hseparator14 = gtk_hseparator_new ();
  gtk_widget_show (hseparator14);
  gtk_box_pack_start (GTK_BOX (vbox46), hseparator14, TRUE, TRUE, 0);
  gtk_widget_set_size_request (hseparator14, 1, 10);

  check_att2_name = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att2_name);
  gtk_box_pack_start (GTK_BOX (vbox46), check_att2_name, FALSE, FALSE, 0);

  check_att2_cpos = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att2_cpos);
  gtk_box_pack_start (GTK_BOX (vbox46), check_att2_cpos, FALSE, FALSE, 0);

  check_att2_pos = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att2_pos);
  gtk_box_pack_start (GTK_BOX (vbox46), check_att2_pos, FALSE, FALSE, 0);

  check_att2_cskill = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att2_cskill);
  gtk_box_pack_start (GTK_BOX (vbox46), check_att2_cskill, FALSE, FALSE, 0);

  check_att2_skill = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att2_skill);
  gtk_box_pack_start (GTK_BOX (vbox46), check_att2_skill, FALSE, FALSE, 0);

  check_att2_fit = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att2_fit);
  gtk_box_pack_start (GTK_BOX (vbox46), check_att2_fit, FALSE, FALSE, 0);

  check_att2_games = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att2_games);
  gtk_box_pack_start (GTK_BOX (vbox46), check_att2_games, FALSE, FALSE, 0);

  check_att2_goals = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att2_goals);
  gtk_box_pack_start (GTK_BOX (vbox46), check_att2_goals, FALSE, FALSE, 0);

  check_att2_status = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att2_status);
  gtk_box_pack_start (GTK_BOX (vbox46), check_att2_status, FALSE, FALSE, 0);

  check_att2_age = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att2_age);
  gtk_box_pack_start (GTK_BOX (vbox46), check_att2_age, FALSE, FALSE, 0);

  check_att2_etal = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att2_etal);
  gtk_box_pack_start (GTK_BOX (vbox46), check_att2_etal, FALSE, FALSE, 0);

  check_att2_booked = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att2_booked);
  gtk_box_pack_start (GTK_BOX (vbox46), check_att2_booked, FALSE, FALSE, 0);

  check_att2_value = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att2_value);
  gtk_box_pack_start (GTK_BOX (vbox46), check_att2_value, FALSE, FALSE, 0);

  check_att2_wage = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att2_wage);
  gtk_box_pack_start (GTK_BOX (vbox46), check_att2_wage, FALSE, FALSE, 0);

  check_att2_team = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att2_team);
  gtk_box_pack_start (GTK_BOX (vbox46), check_att2_team, FALSE, FALSE, 0);

  check_att2_league = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (check_att2_league);
  gtk_box_pack_start (GTK_BOX (vbox46), check_att2_league, FALSE, FALSE, 0);

  label93 = gtk_label_new (_("Player attributes that are shown in the two player lists"));
  gtk_widget_show (label93);
  gtk_frame_set_label_widget (GTK_FRAME (frame5), label93);

  label87 = gtk_label_new (_("Player attributes"));
  gtk_widget_show (label87);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label87);

  frame8 = gtk_frame_new (NULL);
  gtk_widget_show (frame8);
  gtk_container_add (GTK_CONTAINER (notebook1), frame8);
  gtk_container_set_border_width (GTK_CONTAINER (frame8), 5);

  hbox69 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox69);
  gtk_container_add (GTK_CONTAINER (frame8), hbox69);

  vbox50 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox50);
  gtk_box_pack_start (GTK_BOX (hbox69), vbox50, TRUE, TRUE, 0);

  label136 = gtk_label_new (_("Option"));
  gtk_widget_show (label136);
  gtk_box_pack_start (GTK_BOX (vbox50), label136, FALSE, FALSE, 0);

  hseparator17 = gtk_hseparator_new ();
  gtk_widget_show (hseparator17);
  gtk_box_pack_start (GTK_BOX (vbox50), hseparator17, FALSE, TRUE, 0);
  gtk_widget_set_size_request (hseparator17, 1, 10);

  vbox51 = gtk_vbox_new (FALSE, 8);
  gtk_widget_show (vbox51);
  gtk_box_pack_start (GTK_BOX (vbox50), vbox51, TRUE, TRUE, 0);

  eventbox4 = gtk_event_box_new ();
  gtk_widget_show (eventbox4);
  gtk_box_pack_start (GTK_BOX (vbox51), eventbox4, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, eventbox4, _("How often new data is added to the history."), NULL);

  label140 = gtk_label_new (_("Update interval (in weeks)"));
  gtk_widget_show (label140);
  gtk_container_add (GTK_CONTAINER (eventbox4), label140);

  eventbox5 = gtk_event_box_new ();
  gtk_widget_show (eventbox5);
  gtk_box_pack_start (GTK_BOX (vbox51), eventbox5, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, eventbox5, _("How long the history can get at most (data from the beginning of the list gets removed afterwards). WARNING: The higher this value is, the more memory is needed, especially for the player histories. Additionally, loading and saving games gets slower."), NULL);

  label141 = gtk_label_new (_("Maximal history length"));
  gtk_widget_show (label141);
  gtk_container_add (GTK_CONTAINER (eventbox5), label141);

  eventbox6 = gtk_event_box_new ();
  gtk_widget_show (eventbox6);
  gtk_box_pack_start (GTK_BOX (vbox51), eventbox6, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, eventbox6, _("Whether each season begins with an empty history list."), NULL);

  label142 = gtk_label_new (_("Delete history at end of season"));
  gtk_widget_show (label142);
  gtk_container_add (GTK_CONTAINER (eventbox6), label142);

  vseparator8 = gtk_vseparator_new ();
  gtk_widget_show (vseparator8);
  gtk_box_pack_start (GTK_BOX (hbox69), vseparator8, TRUE, TRUE, 0);

  vbox48 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox48);
  gtk_box_pack_start (GTK_BOX (hbox69), vbox48, TRUE, TRUE, 0);

  label134 = gtk_label_new (_("Team histories"));
  gtk_widget_show (label134);
  gtk_box_pack_start (GTK_BOX (vbox48), label134, FALSE, FALSE, 0);

  hseparator15 = gtk_hseparator_new ();
  gtk_widget_show (hseparator15);
  gtk_box_pack_start (GTK_BOX (vbox48), hseparator15, FALSE, TRUE, 0);
  gtk_widget_set_size_request (hseparator15, 1, 10);

  spinbutton_interval_team_adj = gtk_adjustment_new (1, 1, 20, 1, 10, 10);
  spinbutton_interval_team = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_interval_team_adj), 1, 0);
  gtk_widget_show (spinbutton_interval_team);
  gtk_box_pack_start (GTK_BOX (vbox48), spinbutton_interval_team, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, spinbutton_interval_team, _("How often new data is added to the history."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_interval_team), TRUE);

  spinbutton_max_team_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton_max_team = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_max_team_adj), 1, 0);
  gtk_widget_show (spinbutton_max_team);
  gtk_box_pack_start (GTK_BOX (vbox48), spinbutton_max_team, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, spinbutton_max_team, _("How long the history can get at most (data from the beginning of the list gets removed afterwards). WARNING: The higher this value is, the more memory is needed, especially for the player histories. Additionally, loading and saving games gets slower."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_max_team), TRUE);

  checkbutton_delete_team = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton_delete_team);
  gtk_box_pack_start (GTK_BOX (vbox48), checkbutton_delete_team, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, checkbutton_delete_team, _("Whether each season begins with an empty history list."), NULL);

  vseparator7 = gtk_vseparator_new ();
  gtk_widget_show (vseparator7);
  gtk_box_pack_start (GTK_BOX (hbox69), vseparator7, FALSE, TRUE, 0);
  gtk_widget_set_size_request (vseparator7, 10, 1);

  vbox49 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox49);
  gtk_box_pack_start (GTK_BOX (hbox69), vbox49, TRUE, TRUE, 0);

  label135 = gtk_label_new (_("Player histories"));
  gtk_widget_show (label135);
  gtk_box_pack_start (GTK_BOX (vbox49), label135, FALSE, FALSE, 0);

  hseparator16 = gtk_hseparator_new ();
  gtk_widget_show (hseparator16);
  gtk_box_pack_start (GTK_BOX (vbox49), hseparator16, FALSE, TRUE, 0);
  gtk_widget_set_size_request (hseparator16, 1, 10);

  spinbutton_interval_player_adj = gtk_adjustment_new (1, 1, 20, 1, 10, 10);
  spinbutton_interval_player = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_interval_player_adj), 1, 0);
  gtk_widget_show (spinbutton_interval_player);
  gtk_box_pack_start (GTK_BOX (vbox49), spinbutton_interval_player, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, spinbutton_interval_player, _("How often new data is added to the history."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_interval_player), TRUE);

  spinbutton_max_player_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton_max_player = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_max_player_adj), 1, 0);
  gtk_widget_show (spinbutton_max_player);
  gtk_box_pack_start (GTK_BOX (vbox49), spinbutton_max_player, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, spinbutton_max_player, _("How long the history can get at most (data from the beginning of the list gets removed afterwards). WARNING: The higher this value is, the more memory is needed, especially for the player histories. Additionally, loading and saving games gets slower."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_max_player), TRUE);

  checkbutton_delete_player = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton_delete_player);
  gtk_box_pack_start (GTK_BOX (vbox49), checkbutton_delete_player, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, checkbutton_delete_player, _("Whether each season begins with an empty history list."), NULL);

  label132 = gtk_label_new (_("Team and player histories"));
  gtk_widget_show (label132);
  gtk_frame_set_label_widget (GTK_FRAME (frame8), label132);

  label131 = gtk_label_new (_("Histories"));
  gtk_widget_show (label131);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), label131);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_show (frame6);
  gtk_container_add (GTK_CONTAINER (notebook1), frame6);
  gtk_container_set_border_width (GTK_CONTAINER (frame6), 5);

  vbox40 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox40);
  gtk_container_add (GTK_CONTAINER (frame6), vbox40);

  checkbutton_skip_weeks = gtk_check_button_new_with_mnemonic (_("Skip weeks when my team doesn't play"));
  gtk_widget_show (checkbutton_skip_weeks);
  gtk_box_pack_start (GTK_BOX (vbox40), checkbutton_skip_weeks, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton_skip_weeks), 2);
  gtk_tooltips_set_tip (tooltips, checkbutton_skip_weeks, _("Unchecking this is particularly useful if you only play an international cup and want to keep a close eye on the transfer list.\nThere's also a drawback: player wages get deduced each week."), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_skip_weeks), TRUE);

  label94 = gtk_label_new (_("Miscellaneous options"));
  gtk_widget_show (label94);
  gtk_frame_set_label_widget (GTK_FRAME (frame6), label94);

  label88 = gtk_label_new (_("Misc"));
  gtk_widget_show (label88);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 6), label88);

  hseparator8 = gtk_hseparator_new ();
  gtk_widget_show (hseparator8);
  gtk_box_pack_start (GTK_BOX (vbox39), hseparator8, TRUE, TRUE, 0);
  gtk_widget_set_size_request (hseparator8, 1, 10);

  hbox25 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox25);
  gtk_box_pack_start (GTK_BOX (vbox39), hbox25, TRUE, TRUE, 0);

  checkbutton_save_conf = gtk_check_button_new_with_mnemonic (_("Save to file"));
  gtk_widget_show (checkbutton_save_conf);
  gtk_box_pack_start (GTK_BOX (hbox25), checkbutton_save_conf, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, checkbutton_save_conf, _("Save options to $HOME/.bygfoot/bygfoot.conf. If you start Bygfoot again, they get loaded from the file."), NULL);

  button_opt_ok = gtk_button_new ();
  gtk_widget_show (button_opt_ok);
  gtk_box_pack_start (GTK_BOX (hbox25), button_opt_ok, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_opt_ok), 3);
  gtk_tooltips_set_tip (tooltips, button_opt_ok, _("Return"), NULL);
  gtk_widget_add_accelerator (button_opt_ok, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_opt_ok), alignment4);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox26);

  image25 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox26), image25, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox26), label47, FALSE, FALSE, 0);

  button_opt_cancel = gtk_button_new ();
  gtk_widget_show (button_opt_cancel);
  gtk_box_pack_start (GTK_BOX (hbox25), button_opt_cancel, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button_opt_cancel), 3);
  gtk_tooltips_set_tip (tooltips, button_opt_cancel, _("Esc"), NULL);
  gtk_widget_add_accelerator (button_opt_cancel, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_opt_cancel), alignment5);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox27);

  image26 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox27), image26, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox27), label48, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) opt_window, "delete_event",
                    G_CALLBACK (on_opt_window_delete_event),
                    NULL);
  g_signal_connect ((gpointer) check_show_live, "toggled",
                    G_CALLBACK (on_check_show_live_toggled),
                    NULL);
  g_signal_connect ((gpointer) spin_live_duration, "activate",
                    G_CALLBACK (on_spin_live_duration_activate),
                    NULL);
  g_signal_connect ((gpointer) button_opt_change_font, "clicked",
                    G_CALLBACK (on_button_opt_change_font_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_autosave, "toggled",
                    G_CALLBACK (on_checkbutton_autosave_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_sort_transfers, "toggled",
                    G_CALLBACK (on_checkbutton_sort_transfers_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_notify, "toggled",
                    G_CALLBACK (on_checkbutton_notify_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_opt_ok, "clicked",
                    G_CALLBACK (on_button_opt_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_opt_cancel, "clicked",
                    G_CALLBACK (on_button_opt_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (opt_window, opt_window, "opt_window");
  GLADE_HOOKUP_OBJECT (opt_window, vbox39, "vbox39");
  GLADE_HOOKUP_OBJECT (opt_window, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (opt_window, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (opt_window, hbox65, "hbox65");
  GLADE_HOOKUP_OBJECT (opt_window, vbox32, "vbox32");
  GLADE_HOOKUP_OBJECT (opt_window, label53, "label53");
  GLADE_HOOKUP_OBJECT (opt_window, hbox66, "hbox66");
  GLADE_HOOKUP_OBJECT (opt_window, radio_show1, "radio_show1");
  GLADE_HOOKUP_OBJECT (opt_window, radio_show2, "radio_show2");
  GLADE_HOOKUP_OBJECT (opt_window, check_show_live, "check_show_live");
  GLADE_HOOKUP_OBJECT (opt_window, vbox34, "vbox34");
  GLADE_HOOKUP_OBJECT (opt_window, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (opt_window, label43, "label43");
  GLADE_HOOKUP_OBJECT (opt_window, spin_live_duration, "spin_live_duration");
  GLADE_HOOKUP_OBJECT (opt_window, hbox39, "hbox39");
  GLADE_HOOKUP_OBJECT (opt_window, label58, "label58");
  GLADE_HOOKUP_OBJECT (opt_window, check_live_tendency, "check_live_tendency");
  GLADE_HOOKUP_OBJECT (opt_window, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (opt_window, button_opt_change_font, "button_opt_change_font");
  GLADE_HOOKUP_OBJECT (opt_window, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (opt_window, hbox35, "hbox35");
  GLADE_HOOKUP_OBJECT (opt_window, image30, "image30");
  GLADE_HOOKUP_OBJECT (opt_window, label55, "label55");
  GLADE_HOOKUP_OBJECT (opt_window, label54, "label54");
  GLADE_HOOKUP_OBJECT (opt_window, hbox46, "hbox46");
  GLADE_HOOKUP_OBJECT (opt_window, label71, "label71");
  GLADE_HOOKUP_OBJECT (opt_window, entry_team_name, "entry_team_name");
  GLADE_HOOKUP_OBJECT (opt_window, vseparator3, "vseparator3");
  GLADE_HOOKUP_OBJECT (opt_window, vbox33, "vbox33");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_maximize, "checkbutton_maximize");
  GLADE_HOOKUP_OBJECT (opt_window, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (opt_window, label45, "label45");
  GLADE_HOOKUP_OBJECT (opt_window, radio_mess1, "radio_mess1");
  GLADE_HOOKUP_OBJECT (opt_window, radio_mess2, "radio_mess2");
  GLADE_HOOKUP_OBJECT (opt_window, radio_mess3, "radio_mess3");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_prefer_mess, "checkbutton_prefer_mess");
  GLADE_HOOKUP_OBJECT (opt_window, check_jobs, "check_jobs");
  GLADE_HOOKUP_OBJECT (opt_window, eventbox3, "eventbox3");
  GLADE_HOOKUP_OBJECT (opt_window, hbox67, "hbox67");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_rearrange, "checkbutton_rearrange");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_swap, "checkbutton_swap");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_fit_colors, "checkbutton_fit_colors");
  GLADE_HOOKUP_OBJECT (opt_window, label89, "label89");
  GLADE_HOOKUP_OBJECT (opt_window, label83, "label83");
  GLADE_HOOKUP_OBJECT (opt_window, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (opt_window, vbox35, "vbox35");
  GLADE_HOOKUP_OBJECT (opt_window, check_overwrite, "check_overwrite");
  GLADE_HOOKUP_OBJECT (opt_window, hbox62, "hbox62");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_autosave, "checkbutton_autosave");
  GLADE_HOOKUP_OBJECT (opt_window, spinbutton_autosave, "spinbutton_autosave");
  GLADE_HOOKUP_OBJECT (opt_window, label82, "label82");
  GLADE_HOOKUP_OBJECT (opt_window, label90, "label90");
  GLADE_HOOKUP_OBJECT (opt_window, label84, "label84");
  GLADE_HOOKUP_OBJECT (opt_window, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (opt_window, vbox36, "vbox36");
  GLADE_HOOKUP_OBJECT (opt_window, hbox63, "hbox63");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_sort_transfers, "checkbutton_sort_transfers");
  GLADE_HOOKUP_OBJECT (opt_window, hbox64, "hbox64");
  GLADE_HOOKUP_OBJECT (opt_window, radiobutton_sort_pos, "radiobutton_sort_pos");
  GLADE_HOOKUP_OBJECT (opt_window, radiobutton_sort_skill, "radiobutton_sort_skill");
  GLADE_HOOKUP_OBJECT (opt_window, radiobutton_sort_age, "radiobutton_sort_age");
  GLADE_HOOKUP_OBJECT (opt_window, radiobutton_sort_etal, "radiobutton_sort_etal");
  GLADE_HOOKUP_OBJECT (opt_window, radiobutton_sort_league, "radiobutton_sort_league");
  GLADE_HOOKUP_OBJECT (opt_window, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_sort_asc, "checkbutton_sort_asc");
  GLADE_HOOKUP_OBJECT (opt_window, hseparator11, "hseparator11");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_notify, "checkbutton_notify");
  GLADE_HOOKUP_OBJECT (opt_window, frame7, "frame7");
  GLADE_HOOKUP_OBJECT (opt_window, hbox52, "hbox52");
  GLADE_HOOKUP_OBJECT (opt_window, vbox28, "vbox28");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_notify_skill, "checkbutton_notify_skill");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_notify_etal, "checkbutton_notify_etal");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_notify_age, "checkbutton_notify_age");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_notify_value, "checkbutton_notify_value");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_notify_positions, "checkbutton_notify_positions");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_notify_league, "checkbutton_notify_league");
  GLADE_HOOKUP_OBJECT (opt_window, label78, "label78");
  GLADE_HOOKUP_OBJECT (opt_window, vbox29, "vbox29");
  GLADE_HOOKUP_OBJECT (opt_window, spinbutton_notify_skill1, "spinbutton_notify_skill1");
  GLADE_HOOKUP_OBJECT (opt_window, spinbutton_notify_etal1, "spinbutton_notify_etal1");
  GLADE_HOOKUP_OBJECT (opt_window, spinbutton_notify_age1, "spinbutton_notify_age1");
  GLADE_HOOKUP_OBJECT (opt_window, spinbutton_notify_value, "spinbutton_notify_value");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_notify_pos0, "checkbutton_notify_pos0");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_notify_league1, "checkbutton_notify_league1");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_notify_league4, "checkbutton_notify_league4");
  GLADE_HOOKUP_OBJECT (opt_window, vbox30, "vbox30");
  GLADE_HOOKUP_OBJECT (opt_window, label73, "label73");
  GLADE_HOOKUP_OBJECT (opt_window, label74, "label74");
  GLADE_HOOKUP_OBJECT (opt_window, label75, "label75");
  GLADE_HOOKUP_OBJECT (opt_window, label76, "label76");
  GLADE_HOOKUP_OBJECT (opt_window, hbox54, "hbox54");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_notify_pos1, "checkbutton_notify_pos1");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_notify_pos2, "checkbutton_notify_pos2");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_notify_league2, "checkbutton_notify_league2");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_notify_league5, "checkbutton_notify_league5");
  GLADE_HOOKUP_OBJECT (opt_window, vboxa31, "vboxa31");
  GLADE_HOOKUP_OBJECT (opt_window, spinbutton_notify_skill2, "spinbutton_notify_skill2");
  GLADE_HOOKUP_OBJECT (opt_window, spinbutton_notify_etal2, "spinbutton_notify_etal2");
  GLADE_HOOKUP_OBJECT (opt_window, spinbutton_notify_age2, "spinbutton_notify_age2");
  GLADE_HOOKUP_OBJECT (opt_window, label77, "label77");
  GLADE_HOOKUP_OBJECT (opt_window, hbox53, "hbox53");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_notify_pos3, "checkbutton_notify_pos3");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_notify_league3, "checkbutton_notify_league3");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_notify_league6, "checkbutton_notify_league6");
  GLADE_HOOKUP_OBJECT (opt_window, label95, "label95");
  GLADE_HOOKUP_OBJECT (opt_window, label91, "label91");
  GLADE_HOOKUP_OBJECT (opt_window, label85, "label85");
  GLADE_HOOKUP_OBJECT (opt_window, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (opt_window, vbox37, "vbox37");
  GLADE_HOOKUP_OBJECT (opt_window, check_conf_new_week, "check_conf_new_week");
  GLADE_HOOKUP_OBJECT (opt_window, check_conf_unfit, "check_conf_unfit");
  GLADE_HOOKUP_OBJECT (opt_window, check_conf_quit, "check_conf_quit");
  GLADE_HOOKUP_OBJECT (opt_window, label92, "label92");
  GLADE_HOOKUP_OBJECT (opt_window, label86, "label86");
  GLADE_HOOKUP_OBJECT (opt_window, frame5, "frame5");
  GLADE_HOOKUP_OBJECT (opt_window, vbox41, "vbox41");
  GLADE_HOOKUP_OBJECT (opt_window, hbox68, "hbox68");
  GLADE_HOOKUP_OBJECT (opt_window, vbox42, "vbox42");
  GLADE_HOOKUP_OBJECT (opt_window, label98, "label98");
  GLADE_HOOKUP_OBJECT (opt_window, hseparator12, "hseparator12");
  GLADE_HOOKUP_OBJECT (opt_window, label109, "label109");
  GLADE_HOOKUP_OBJECT (opt_window, label110, "label110");
  GLADE_HOOKUP_OBJECT (opt_window, label111, "label111");
  GLADE_HOOKUP_OBJECT (opt_window, label112, "label112");
  GLADE_HOOKUP_OBJECT (opt_window, label99, "label99");
  GLADE_HOOKUP_OBJECT (opt_window, label100, "label100");
  GLADE_HOOKUP_OBJECT (opt_window, label101, "label101");
  GLADE_HOOKUP_OBJECT (opt_window, label102, "label102");
  GLADE_HOOKUP_OBJECT (opt_window, label103, "label103");
  GLADE_HOOKUP_OBJECT (opt_window, label104, "label104");
  GLADE_HOOKUP_OBJECT (opt_window, label105, "label105");
  GLADE_HOOKUP_OBJECT (opt_window, label106, "label106");
  GLADE_HOOKUP_OBJECT (opt_window, label107, "label107");
  GLADE_HOOKUP_OBJECT (opt_window, label108, "label108");
  GLADE_HOOKUP_OBJECT (opt_window, label113, "label113");
  GLADE_HOOKUP_OBJECT (opt_window, label114, "label114");
  GLADE_HOOKUP_OBJECT (opt_window, vseparator6, "vseparator6");
  GLADE_HOOKUP_OBJECT (opt_window, vbox45, "vbox45");
  GLADE_HOOKUP_OBJECT (opt_window, label130, "label130");
  GLADE_HOOKUP_OBJECT (opt_window, hseparator13, "hseparator13");
  GLADE_HOOKUP_OBJECT (opt_window, check_att_name, "check_att_name");
  GLADE_HOOKUP_OBJECT (opt_window, check_att_cpos, "check_att_cpos");
  GLADE_HOOKUP_OBJECT (opt_window, check_att_pos, "check_att_pos");
  GLADE_HOOKUP_OBJECT (opt_window, check_att_cskill, "check_att_cskill");
  GLADE_HOOKUP_OBJECT (opt_window, check_att_skill, "check_att_skill");
  GLADE_HOOKUP_OBJECT (opt_window, check_att_fit, "check_att_fit");
  GLADE_HOOKUP_OBJECT (opt_window, check_att_games, "check_att_games");
  GLADE_HOOKUP_OBJECT (opt_window, check_att_goals, "check_att_goals");
  GLADE_HOOKUP_OBJECT (opt_window, check_att_status, "check_att_status");
  GLADE_HOOKUP_OBJECT (opt_window, check_att_age, "check_att_age");
  GLADE_HOOKUP_OBJECT (opt_window, check_att_etal, "check_att_etal");
  GLADE_HOOKUP_OBJECT (opt_window, check_att_booked, "check_att_booked");
  GLADE_HOOKUP_OBJECT (opt_window, check_att_value, "check_att_value");
  GLADE_HOOKUP_OBJECT (opt_window, check_att_wage, "check_att_wage");
  GLADE_HOOKUP_OBJECT (opt_window, check_att_team, "check_att_team");
  GLADE_HOOKUP_OBJECT (opt_window, check_att_league, "check_att_league");
  GLADE_HOOKUP_OBJECT (opt_window, vseparator5, "vseparator5");
  GLADE_HOOKUP_OBJECT (opt_window, vbox46, "vbox46");
  GLADE_HOOKUP_OBJECT (opt_window, label115, "label115");
  GLADE_HOOKUP_OBJECT (opt_window, hseparator14, "hseparator14");
  GLADE_HOOKUP_OBJECT (opt_window, check_att2_name, "check_att2_name");
  GLADE_HOOKUP_OBJECT (opt_window, check_att2_cpos, "check_att2_cpos");
  GLADE_HOOKUP_OBJECT (opt_window, check_att2_pos, "check_att2_pos");
  GLADE_HOOKUP_OBJECT (opt_window, check_att2_cskill, "check_att2_cskill");
  GLADE_HOOKUP_OBJECT (opt_window, check_att2_skill, "check_att2_skill");
  GLADE_HOOKUP_OBJECT (opt_window, check_att2_fit, "check_att2_fit");
  GLADE_HOOKUP_OBJECT (opt_window, check_att2_games, "check_att2_games");
  GLADE_HOOKUP_OBJECT (opt_window, check_att2_goals, "check_att2_goals");
  GLADE_HOOKUP_OBJECT (opt_window, check_att2_status, "check_att2_status");
  GLADE_HOOKUP_OBJECT (opt_window, check_att2_age, "check_att2_age");
  GLADE_HOOKUP_OBJECT (opt_window, check_att2_etal, "check_att2_etal");
  GLADE_HOOKUP_OBJECT (opt_window, check_att2_booked, "check_att2_booked");
  GLADE_HOOKUP_OBJECT (opt_window, check_att2_value, "check_att2_value");
  GLADE_HOOKUP_OBJECT (opt_window, check_att2_wage, "check_att2_wage");
  GLADE_HOOKUP_OBJECT (opt_window, check_att2_team, "check_att2_team");
  GLADE_HOOKUP_OBJECT (opt_window, check_att2_league, "check_att2_league");
  GLADE_HOOKUP_OBJECT (opt_window, label93, "label93");
  GLADE_HOOKUP_OBJECT (opt_window, label87, "label87");
  GLADE_HOOKUP_OBJECT (opt_window, frame8, "frame8");
  GLADE_HOOKUP_OBJECT (opt_window, hbox69, "hbox69");
  GLADE_HOOKUP_OBJECT (opt_window, vbox50, "vbox50");
  GLADE_HOOKUP_OBJECT (opt_window, label136, "label136");
  GLADE_HOOKUP_OBJECT (opt_window, hseparator17, "hseparator17");
  GLADE_HOOKUP_OBJECT (opt_window, vbox51, "vbox51");
  GLADE_HOOKUP_OBJECT (opt_window, eventbox4, "eventbox4");
  GLADE_HOOKUP_OBJECT (opt_window, label140, "label140");
  GLADE_HOOKUP_OBJECT (opt_window, eventbox5, "eventbox5");
  GLADE_HOOKUP_OBJECT (opt_window, label141, "label141");
  GLADE_HOOKUP_OBJECT (opt_window, eventbox6, "eventbox6");
  GLADE_HOOKUP_OBJECT (opt_window, label142, "label142");
  GLADE_HOOKUP_OBJECT (opt_window, vseparator8, "vseparator8");
  GLADE_HOOKUP_OBJECT (opt_window, vbox48, "vbox48");
  GLADE_HOOKUP_OBJECT (opt_window, label134, "label134");
  GLADE_HOOKUP_OBJECT (opt_window, hseparator15, "hseparator15");
  GLADE_HOOKUP_OBJECT (opt_window, spinbutton_interval_team, "spinbutton_interval_team");
  GLADE_HOOKUP_OBJECT (opt_window, spinbutton_max_team, "spinbutton_max_team");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_delete_team, "checkbutton_delete_team");
  GLADE_HOOKUP_OBJECT (opt_window, vseparator7, "vseparator7");
  GLADE_HOOKUP_OBJECT (opt_window, vbox49, "vbox49");
  GLADE_HOOKUP_OBJECT (opt_window, label135, "label135");
  GLADE_HOOKUP_OBJECT (opt_window, hseparator16, "hseparator16");
  GLADE_HOOKUP_OBJECT (opt_window, spinbutton_interval_player, "spinbutton_interval_player");
  GLADE_HOOKUP_OBJECT (opt_window, spinbutton_max_player, "spinbutton_max_player");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_delete_player, "checkbutton_delete_player");
  GLADE_HOOKUP_OBJECT (opt_window, label132, "label132");
  GLADE_HOOKUP_OBJECT (opt_window, label131, "label131");
  GLADE_HOOKUP_OBJECT (opt_window, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (opt_window, vbox40, "vbox40");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_skip_weeks, "checkbutton_skip_weeks");
  GLADE_HOOKUP_OBJECT (opt_window, label94, "label94");
  GLADE_HOOKUP_OBJECT (opt_window, label88, "label88");
  GLADE_HOOKUP_OBJECT (opt_window, hseparator8, "hseparator8");
  GLADE_HOOKUP_OBJECT (opt_window, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (opt_window, checkbutton_save_conf, "checkbutton_save_conf");
  GLADE_HOOKUP_OBJECT (opt_window, button_opt_ok, "button_opt_ok");
  GLADE_HOOKUP_OBJECT (opt_window, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (opt_window, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (opt_window, image25, "image25");
  GLADE_HOOKUP_OBJECT (opt_window, label47, "label47");
  GLADE_HOOKUP_OBJECT (opt_window, button_opt_cancel, "button_opt_cancel");
  GLADE_HOOKUP_OBJECT (opt_window, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (opt_window, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (opt_window, image26, "image26");
  GLADE_HOOKUP_OBJECT (opt_window, label48, "label48");
  GLADE_HOOKUP_OBJECT_NO_REF (opt_window, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (opt_window), accel_group);

  return opt_window;
}

